# Generated by Django 4.2.27 on 2026-01-19 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g., ATTENDANCE_SYSTEM', max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('CORE', 'Core (Cannot be disabled)'), ('STANDARD', 'Standard'), ('ADVANCED', 'Advanced/Add-on')], default='STANDARD', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('default_enabled', models.BooleanField(default=False)),
                ('dependencies', models.TextField(blank=True, default='[]', help_text='List of feature codes this depends on')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFeatureConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('config_json', models.TextField(blank=True, default='{}', help_text='School-specific settings (DNA)')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='features.feature')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_configs', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'feature')},
            },
        ),
    ]
