# Generated by Django 4.2.16 on 2026-01-22 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gatepass', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gatepass',
            old_name='issued_at',
            new_name='requested_at',
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approval_note',
            field=models.TextField(blank=True, help_text='Note from approver'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='approved_by_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_gatepasses', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='out_time',
            field=models.TimeField(blank=True, help_text='Expected time to leave school', null=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='requested_by',
            field=models.ForeignKey(help_text='Who requested the gate pass (student/parent/admin)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_gatepasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='issued_by',
            field=models.ForeignKey(blank=True, help_text='Who approved and issued the pass', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_gatepasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active (Ready to Scan)'), ('USED', 'Used (Student Left)'), ('EXPIRED', 'Expired (Not Used)')], default='PENDING', max_length=20),
        ),
    ]
