# Generated by Django 4.2.27 on 2026-01-27 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0002_rename_issued_at_gatepass_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='issued_at',
            field=models.DateTimeField(blank=True, help_text='When the pass was issued', null=True),
        ),
    ]
