# Generated by Django 4.2.16 on 2026-04-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0003_gatepass_issued_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='qr_signature',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
