# Generated by Django 4.2.16 on 2026-05-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0004_gatepass_qr_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='failed_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gatepass',
            name='secret_key',
            field=models.CharField(blank=True, help_text='6-digit numeric code', max_length=6, null=True),
        ),
    ]
