# Generated by Django 4.2.16 on 2026-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0005_gatepass_failed_attempts_gatepass_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='secret_key',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
