# Generated by Django 4.2.16 on 2026-05-06 16:10

import apps.gatepass.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0006_alter_gatepass_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='pass_id',
            field=models.CharField(default=apps.gatepass.models.generate_pass_id, max_length=8, unique=True),
        ),
    ]
