# Generated by Django 4.2.16 on 2026-05-07 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0007_gatepass_pass_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gatepass',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ACTIVE', 'Active (Ready to Scan)'), ('USED', 'Used (Student Left)'), ('EXPIRED', 'Expired (Not Used)'), ('CANCELLED', 'Cancelled (Terminated)')], default='PENDING', max_length=20),
        ),
    ]
