# Generated by Django 4.2.16 on 2026-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gatepass', '0009_visitorpass'),
    ]

    operations = [
        migrations.AddField(
            model_name='gatepass',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='visitorpass',
            name='cancellation_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
