# Generated by Django 4.2.16 on 2026-05-09 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_schoolsettings_gatepass_app_password_and_more'),
        ('assets', '0002_asset_purchased_for_alter_asset_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('AUDIT', 'Audit'), ('MAINTENANCE', 'Maintenance')], max_length=20)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='assets.asset')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
