# Generated by Django 4.2.16 on 2026-05-09 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0014_schoolsettings_gatepass_app_password_and_more'),
        ('assets', '0003_assetschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sale_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sale', to='assets.asset')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
