# Generated by Django 4.2.16 on 2026-05-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_assetsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetschedule',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='asset_reports/'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
