# Generated by Django 4.2.16 on 2026-06-25 13:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollmentArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_global_id', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('school_name', models.CharField(max_length=200)),
                ('admission_details', models.JSONField()),
                ('documents', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Student Enrollment Archive Record',
                'verbose_name_plural': 'Student Enrollment Archive Records',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineHealth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_global_id', models.CharField(db_index=True, max_length=50)),
                ('visit_date', models.DateTimeField()),
                ('symptom', models.CharField(max_length=200)),
                ('treatment_given', models.TextField()),
                ('sent_home', models.BooleanField(default=False)),
                ('recorded_by', models.CharField(max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Health Log',
                'verbose_name_plural': 'Timeline Health Logs',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='TimelineMark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_global_id', models.CharField(db_index=True, max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('exam_name', models.CharField(max_length=100)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('total_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('passing_marks', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_pass', models.BooleanField(default=False)),
                ('is_absent', models.BooleanField(default=False)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Mark',
                'verbose_name_plural': 'Timeline Marks',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='TimelineRemark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_global_id', models.CharField(db_index=True, max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('record_type', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField(blank=True, null=True)),
                ('teacher_name', models.CharField(blank=True, max_length=200)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Timeline Remark',
                'verbose_name_plural': 'Timeline Remarks',
                'ordering': ['-recorded_at'],
            },
        ),
    ]
