# Generated by Django 4.2.16 on 2026-06-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_timelinemark_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollmentarchive',
            name='timeline_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
