# Generated by Django 4.2.16 on 2026-06-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0003_studentenrollmentarchive_timeline_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelinehealth',
            name='grade',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
