# Generated by Django 4.2.16 on 2026-06-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0004_timelinehealth_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentenrollmentarchive',
            name='re_admitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentenrollmentarchive',
            name='re_admitted_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollmentarchive',
            name='re_admitted_to_school_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='studentenrollmentarchive',
            name='transferred_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
