# Generated by Django 4.2.16 on 2026-06-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_exam_assessment_category'),
        ('attendance', '0002_alter_attendancesession_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='academics.subject'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('grade', 'section', 'date', 'session_type', 'subject')},
        ),
    ]
