# Generated by Django 4.2.16 on 2026-06-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_result_aggregated_internal_marks_and_more'),
        ('schools', '0018_schoolsettings_gatepass_creation_email_body_and_more'),
        ('attendance', '0003_alter_attendancesession_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='schools.school'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesession',
            unique_together={('school', 'grade', 'section', 'date', 'session_type', 'subject')},
        ),
    ]
