# Generated by Django 4.2.27 on 2026-01-19 11:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('SUBJECT_TEACHER', 'Subject Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBSTITUTE', 'Substitute / Proxy'), ('BACKEND_ADMIN', 'Backend / Exam Dept')], max_length=20)),
                ('grade', models.CharField(help_text='Target Grade', max_length=10)),
                ('section', models.CharField(help_text='Target Section', max_length=5)),
                ('subject', models.CharField(blank=True, help_text='e.g. Mathematics', max_length=100, null=True)),
                ('academic_year', models.CharField(help_text='2025-2026', max_length=9)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_assignments', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Teacher Assignment',
                'ordering': ['school', 'academic_year', 'grade'],
            },
        ),
    ]
