# Generated by Django 4.2.16 on 2026-01-20 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        ('teachers', '0002_teacherassignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='awards',
            field=models.TextField(blank=True, default='', help_text='Professional awards & recognitions'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='certified_subjects',
            field=models.TextField(default='', help_text='Comma-separated subjects'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='teacher',
            name='verification_status',
            field=models.CharField(choices=[('UNVERIFIED', 'Unverified'), ('VERIFIED', 'Verified')], default='UNVERIFIED', max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualifications',
            field=models.TextField(default='', help_text='e.g. MSc Math, B.Ed'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='tuid',
            field=models.CharField(editable=False, help_text='T-YYYY-XXXXXX format', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='grade',
            field=models.CharField(blank=True, help_text='Target Grade', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='role',
            field=models.CharField(choices=[('SUBJECT_TEACHER', 'Subject Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBSTITUTE', 'Substitute / Proxy'), ('EXAM_INVIGILATOR', 'Exam Invigilator'), ('SPORTS_TEACHER', 'Sports / Activity Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='section',
            field=models.CharField(blank=True, help_text='Target Section', max_length=5),
        ),
        migrations.CreateModel(
            name='TeacherSchoolAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joining_date', models.DateField()),
                ('relieving_date', models.DateField(blank=True, null=True)),
                ('employment_type', models.CharField(choices=[('FULL_TIME', 'Full-time'), ('PART_TIME', 'Part-time'), ('CONTRACT', 'Contract')], default='FULL_TIME', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_associations', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_associations', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-joining_date'],
            },
        ),
    ]
