# Generated by Django 4.2.16 on 2026-01-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='tuid',
            field=models.CharField(editable=False, help_text='T-YYYY-XXXXXX format', max_length=50, unique=True),
        ),
    ]
