# Generated by Django 4.2.16 on 2026-04-26 16:28

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_teacher_aadhaar_last_4_digits_teacher_blood_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherEfficiency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('punctuality_index', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('appraisal_rating', models.PositiveSmallIntegerField(default=3)),
                ('observation_notes', models.JSONField(blank=True, default=list)),
                ('curriculum_completion', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('student_performance_impact', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_appraisal_date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='efficiency_metrics', to='teachers.teacher')),
            ],
            options={
                'verbose_name_plural': 'Teacher Efficiency Metrics',
            },
        ),
    ]
