# Generated by Django 4.2.16 on 2026-06-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_teacher_date_of_joining_teacher_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='teacher_type',
            field=models.CharField(choices=[('TEACHING', 'Teaching'), ('NON_TEACHING', 'Non-Teaching')], default='TEACHING', max_length=20),
        ),
    ]
