# Generated by Django 4.2.16 on 2026-08-02 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teacher_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherassignment',
            name='department',
            field=models.CharField(blank=True, help_text='Department name for non-teaching staff', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherassignment',
            name='role',
            field=models.CharField(choices=[('SUBJECT_TEACHER', 'Subject Teacher'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBSTITUTE', 'Substitute / Proxy'), ('EXAM_INVIGILATOR', 'Exam Invigilator'), ('SPORTS_TEACHER', 'Sports / Activity Teacher'), ('NON_TEACHING_STAFF', 'Non-Teaching Staff'), ('ACCOUNTANT', 'Accountant'), ('LIBRARIAN', 'Librarian'), ('LAB_ASSISTANT', 'Lab Assistant'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('NURSE', 'Nurse / Medical Officer'), ('SECURITY_SUPERVISOR', 'Security Supervisor'), ('IT_SUPPORT', 'IT Support Specialist'), ('FACILITIES_MANAGER', 'Facilities Manager'), ('OFFICE_STAFF', 'Office Staff'), ('COUNSELOR', 'Counselor')], max_length=100),
        ),
    ]
