# Generated by Django 4.2.16 on 2026-01-21 06:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('primary_color', models.CharField(default='#3B82F6', help_text='Hex color code', max_length=7)),
                ('show_student_stats', models.BooleanField(default=True)),
                ('show_teacher_stats', models.BooleanField(default=True)),
                ('show_attendance_widget', models.BooleanField(default=True)),
                ('show_finance_widget', models.BooleanField(default=True)),
                ('show_health_widget', models.BooleanField(default=True)),
                ('show_gatepass_widget', models.BooleanField(default=True)),
                ('show_achievements_widget', models.BooleanField(default=True)),
                ('show_transfers_widget', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=True)),
                ('academic_year_format', models.CharField(choices=[('YYYY-YYYY', '2025-2026'), ('YYYY/YYYY', '2025/2026'), ('YY-YY', '25-26')], default='YYYY-YYYY', max_length=20)),
                ('show_student_photos', models.BooleanField(default=True)),
                ('show_parent_contact', models.BooleanField(default=True)),
                ('show_financial_data', models.BooleanField(default=True)),
                ('default_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('date_format', models.CharField(choices=[('DD/MM/YYYY', 'DD/MM/YYYY'), ('MM/DD/YYYY', 'MM/DD/YYYY'), ('YYYY-MM-DD', 'YYYY-MM-DD')], default='DD/MM/YYYY', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='schools.school')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Settings',
                'verbose_name_plural': 'School Settings',
            },
        ),
    ]
