# Generated by Django 4.2.16 on 2026-01-21 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_schoolsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='allow_continuation_after_10',
            field=models.BooleanField(default=True, help_text='Allow students to continue to 11-12 after Grade 10'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='graduation_point',
            field=models.CharField(choices=[('10', 'After Grade 10'), ('12', 'After Grade 12')], default='12', help_text='Grade level at which students graduate', max_length=10),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='show_alumni_stats',
            field=models.BooleanField(default=True, help_text='Show alumni statistics on dashboard'),
        ),
    ]
