# Generated by Django 4.2.16 on 2026-01-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolsettings_allow_continuation_after_10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_class_teacher_attendance_edit',
            field=models.BooleanField(default=True, help_text='Allow class teachers to edit full-day attendance'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_class_teacher_gatepass_approval',
            field=models.BooleanField(default=True, help_text='Allow class teachers to approve gate passes for their class'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='karma_label',
            field=models.CharField(default='Karma', help_text='Custom name for behavior system (Karma, Conduct Points, Behavior Score, etc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='karma_system_enabled',
            field=models.BooleanField(default=True, help_text='Enable behavior/discipline tracking system'),
        ),
    ]
