# Generated by Django 4.2.16 on 2026-01-24 09:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_assignment_assignmentsubmission_and_more'),
        ('schools', '0004_schoolsettings_enable_class_teacher_attendance_edit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g., Unit Test 1, Mid-Term, Final Exam', max_length=100)),
                ('code', models.CharField(help_text='e.g., UT1, MID, FINAL', max_length=20)),
                ('weightage_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight of this exam type in final grade', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_marks', models.PositiveIntegerField(default=100, help_text='Default maximum marks')),
                ('passing_marks_percent', models.DecimalField(decimal_places=2, default=33, help_text='Passing percentage for this exam type', max_digits=5)),
                ('category', models.CharField(choices=[('WRITTEN', 'Written Exam'), ('PRACTICAL', 'Practical/Lab'), ('PROJECT', 'Project Work'), ('ORAL', 'Oral/Viva'), ('ASSIGNMENT', 'Assignment Based'), ('INTERNAL', 'Internal Assessment')], default='WRITTEN', max_length=20)),
                ('applicable_terms', models.JSONField(blank=True, default=list, help_text='List of term numbers this exam applies to. Empty = all terms.')),
                ('sequence', models.PositiveSmallIntegerField(default=1, help_text='Order of exam in term')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_types', to='schools.school')),
            ],
            options={
                'verbose_name': 'Exam Type',
                'ordering': ['sequence', 'name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SchoolAcademicConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year_start_month', models.PositiveSmallIntegerField(default=4, help_text='Month when academic year starts (1=Jan, 4=April, etc.)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('grading_system', models.CharField(choices=[('PERCENTAGE', 'Percentage Based'), ('CGPA', 'CGPA (10 Point)'), ('LETTER', 'Letter Grades (A-F)'), ('CUSTOM', 'Custom Grading')], default='PERCENTAGE', max_length=20)),
                ('attendance_weightage_enabled', models.BooleanField(default=False, help_text='Include attendance percentage in final score calculation')),
                ('attendance_weightage_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight of attendance in final score (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('minimum_attendance_percent', models.DecimalField(decimal_places=2, default=75, help_text='Minimum attendance required for promotion', max_digits=5)),
                ('assignments_enabled', models.BooleanField(default=True, help_text='Enable assignment tracking system')),
                ('assignments_weightage_enabled', models.BooleanField(default=False, help_text='Include assignment scores in final grade')),
                ('assignments_weightage_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage weight of assignments in final score', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('auto_promotion_enabled', models.BooleanField(default=False, help_text='Automatically promote students meeting criteria')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='academic_config', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Academic Configuration',
                'verbose_name_plural': 'School Academic Configurations',
            },
        ),
        migrations.CreateModel(
            name='GradeTermConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('term_system', models.CharField(choices=[('ANNUAL', 'Annual (1 Term)'), ('SEMESTER', 'Semester (2 Terms)'), ('TRIMESTER', 'Trimester (3 Terms)'), ('QUARTERLY', 'Quarterly (4 Terms)'), ('CUSTOM', 'Custom')], default='SEMESTER', max_length=20)),
                ('number_of_terms', models.PositiveSmallIntegerField(default=2, help_text='Number of terms/semesters in academic year', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='term_configs', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_term_configs', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grade Term Configuration',
                'unique_together': {('school', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='GradeExamStructure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weightage_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override default weightage for this grade. Leave empty to use exam type default.', max_digits=5, null=True)),
                ('max_marks_override', models.PositiveIntegerField(blank=True, help_text='Override max marks for this grade', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this exam mandatory for this grade?')),
                ('exam_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_structures', to='schools.examtype')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_structures', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_exam_structures', to='schools.school')),
            ],
            options={
                'verbose_name': 'Grade Exam Structure',
                'unique_together': {('school', 'grade', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='CustomGradeScale',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_letter', models.CharField(help_text='e.g., A+, A, B+, B, C, D, F', max_length=5)),
                ('min_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('grade_points', models.DecimalField(decimal_places=2, default=0, help_text='Grade points (for CGPA calculation)', max_digits=4)),
                ('description', models.CharField(blank=True, help_text='e.g., Excellent, Good, Average', max_length=50)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='schools.school')),
            ],
            options={
                'verbose_name': 'Custom Grade Scale',
                'ordering': ['-min_percentage'],
                'unique_together': {('school', 'grade_letter')},
            },
        ),
    ]
