# Generated by Django 4.2.16 on 2026-01-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_broadcastnotification_adminnote_broadcastreadreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='auto_apply_late_fee',
            field=models.BooleanField(default=True, help_text='Automatically apply late fees to overdue invoices'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='auto_generate_installment_invoices',
            field=models.BooleanField(default=False, help_text='Automatically generate invoices when installments are due'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='days_before_due_to_generate',
            field=models.PositiveIntegerField(default=7, help_text='Days before due date to auto-generate invoice'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='prevent_duplicate_billing',
            field=models.BooleanField(default=True, help_text='Prevent generating duplicate invoices for same student & installment'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='reminder_days_before_due',
            field=models.PositiveIntegerField(default=3, help_text='Days before due date to send reminder'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='require_billing_confirmation',
            field=models.BooleanField(default=True, help_text='Show confirmation dialog before generating invoice'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='send_payment_reminders',
            field=models.BooleanField(default=True, help_text='Send automated payment reminders'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='show_fee_breakdown_on_invoice',
            field=models.BooleanField(default=True, help_text='Show detailed fee breakdown on invoices'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='show_student_fee_history_on_invoice',
            field=models.BooleanField(default=True, help_text="Show student's fee history when creating invoice"),
        ),
    ]
