# Generated by Django 4.2.27 on 2026-01-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_schoolsettings_auto_apply_late_fee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='enable_gatepass_print',
            field=models.BooleanField(default=False, help_text='Show a print icon on the digital pass QR so staff can print the pass'),
        ),
    ]
