# Generated by Django 4.2.16 on 2026-01-31 07:27

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0009_schoolsettings_enable_gatepass_print'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='name',
        ),
        migrations.AddField(
            model_name='school',
            name='academic_year_start_month',
            field=models.IntegerField(default=4, help_text='Month when academic year starts (1-12)'),
        ),
        migrations.AddField(
            model_name='school',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='school',
            name='agreement_accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='country',
            field=models.CharField(default='India', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='default_currency',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='school',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='display_name',
            field=models.CharField(blank=True, help_text='Display name for UI', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='gst_number',
            field=models.CharField(blank=True, help_text='GST number if applicable', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='legal_name',
            field=models.CharField(blank=True, help_text='Official legal name of the school', max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='school_logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='onboarding_status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ONBOARDING', 'Onboarding'), ('LIVE', 'Live'), ('SUSPENDED', 'Suspended')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='onboarding_step',
            field=models.IntegerField(default=0, help_text='Current step in onboarding wizard (0-11)'),
        ),
        migrations.AddField(
            model_name='school',
            name='primary_language',
            field=models.CharField(default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='registration_number',
            field=models.CharField(blank=True, help_text='School registration number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='subdomain',
            field=models.CharField(blank=True, help_text='schoolname.schoolos.in', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='school',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
        migrations.AddField(
            model_name='school',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='board',
            field=models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('IGCSE', 'IGCSE'), ('IB', 'IB'), ('STATE', 'State Board'), ('SSC', 'SSC (State Board)'), ('CUSTOM', 'Custom')], default='CBSE', help_text='Default board (deprecated - use Academic Programs)', max_length=10),
        ),
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Campus name (e.g., Main Campus, North Branch)', max_length=255)),
                ('code', models.CharField(help_text='Campus code (e.g., MAIN, NORTH)', max_length=50)),
                ('address', models.TextField()),
                ('is_primary', models.BooleanField(default=False, help_text='Is this the primary/main campus?')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campuses', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['-is_primary', 'name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='AcademicProgram',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Program name (e.g., Primary Wing, ICSE Section)', max_length=255)),
                ('code', models.CharField(help_text='Program code (e.g., PRI, SEC)', max_length=50)),
                ('board', models.CharField(choices=[('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('SSC', 'State Board (SSC)'), ('IB', 'International Baccalaureate'), ('IGCSE', 'IGCSE'), ('CUSTOM', 'Custom')], max_length=20)),
                ('education_level', models.CharField(blank=True, choices=[('PRE_PRIMARY', 'Pre-Primary'), ('PRIMARY', 'Primary'), ('MIDDLE', 'Middle School'), ('SECONDARY', 'Secondary'), ('SENIOR_SECONDARY', 'Senior Secondary')], help_text='Optional - for analytics only', max_length=20, null=True)),
                ('medium_of_instruction', models.CharField(default='English', max_length=100)),
                ('evaluation_system', models.CharField(choices=[('MARKS', 'Marks Based'), ('GRADES', 'Grade Based'), ('HYBRID', 'Hybrid')], default='MARKS', max_length=20)),
                ('academic_pattern', models.CharField(choices=[('ANNUAL', 'Annual'), ('SEMESTER', 'Semester'), ('TERM', 'Term')], default='ANNUAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='schools.campus')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_programs', to='schools.school')),
            ],
            options={
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'code')},
            },
        ),
        migrations.CreateModel(
            name='GradeConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade_name', models.CharField(help_text='Grade name as TEXT (LKG, UKG, 1, 2, etc.)', max_length=50)),
                ('grade_order', models.IntegerField(help_text='Numeric order for sorting (1, 2, 3...)')),
                ('max_sections', models.IntegerField(default=1, help_text='Maximum number of sections for this grade')),
                ('default_section_names', models.JSONField(default=list, help_text='Default section names (e.g., ["A", "B", "C"])')),
                ('section_capacity', models.IntegerField(blank=True, help_text='Student capacity per section', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='schools.academicprogram')),
            ],
            options={
                'ordering': ['program', 'grade_order'],
                'unique_together': {('program', 'grade_name')},
            },
        ),
    ]
