# Generated by Django 4.2.16 on 2026-01-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0010_remove_school_name_school_academic_year_start_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradeexamstructure',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_structures', to='schools.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='gradetermconfig',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='term_configs', to='schools.gradeconfiguration'),
        ),
    ]
