# Generated by Django 4.2.16 on 2026-01-31 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_migrate_to_grade_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_holidays', to='schools.school'),
        ),
    ]
