# Generated by Django 4.2.16 on 2026-04-21 13:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_cleanup_grade_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='gatepass_secret_key',
            field=models.CharField(default=uuid.uuid4, help_text='Master Secret Key for QR Code generation and verification', max_length=100),
        ),
    ]
