# Generated by Django 4.2.16 on 2026-05-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0013_schoolsettings_gatepass_secret_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='gatepass_app_password',
            field=models.CharField(blank=True, help_text='Gmail App Password', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='gatepass_sender_email',
            field=models.EmailField(blank=True, help_text='Gmail ID for Gate Pass notifications', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='gatepass_verification_base_url',
            field=models.URLField(default='http://localhost:3000', help_text='Base URL for QR verification link (e.g., http://localhost:3000)'),
        ),
    ]
