# Generated by Django 4.2.16 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0015_school_latitude_school_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='school_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='school_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
