# Generated by Django 4.2.16 on 2026-05-12 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0016_schoolsettings_school_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_latitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='school_longitude',
            field=models.DecimalField(blank=True, decimal_places=9, max_digits=12, null=True),
        ),
    ]
