# Generated by Django 4.2.16 on 2026-06-09 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_alter_schoolsettings_school_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='gatepass_creation_email_body',
            field=models.TextField(blank=True, default='', help_text='Custom email body for gate pass creation (6-digit secret key email)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='gatepass_departure_email_body',
            field=models.TextField(blank=True, default='', help_text='Custom email body for gate pass departure (when child leaves school)'),
        ),
        migrations.AlterField(
            model_name='schoolsettings',
            name='timezone',
            field=models.CharField(default='Asia/Kolkata', max_length=50),
        ),
    ]
