# Generated by Django 4.2.16 on 2026-07-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0019_holiday_created_by_holiday_last_updated_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='last_updated_by',
        ),
        migrations.RemoveField(
            model_name='schoolevent',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='schoolevent',
            name='last_updated_by',
        ),
        migrations.AddField(
            model_name='school',
            name='academic_year_end_day',
            field=models.IntegerField(default=31, help_text='Day when academic year ends (1-31)'),
        ),
        migrations.AddField(
            model_name='school',
            name='academic_year_end_month',
            field=models.IntegerField(default=3, help_text='Month when academic year ends (1-12)'),
        ),
        migrations.AddField(
            model_name='school',
            name='academic_year_start_day',
            field=models.IntegerField(default=1, help_text='Day when academic year starts (1-31)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year_end_day',
            field=models.IntegerField(default=31, help_text='Day when academic year ends (1-31)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year_end_month',
            field=models.IntegerField(default=3, help_text='Month when academic year ends (1-12)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year_start_day',
            field=models.IntegerField(default=1, help_text='Day when academic year starts (1-31)'),
        ),
        migrations.AddField(
            model_name='schoolsettings',
            name='academic_year_start_month',
            field=models.IntegerField(default=4, help_text='Month when academic year starts (1-12)'),
        ),
    ]
