# Generated by Django 4.2.16 on 2026-09-04 08:37

import apps.schools.models_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0020_remove_holiday_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsettings',
            name='required_documents',
            field=models.JSONField(blank=True, default=apps.schools.models_settings.get_default_required_documents),
        ),
    ]
