# Generated by Django 4.2.16 on 2026-09-25 07:09

import apps.schools.models_settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0021_schoolsettings_required_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsettings',
            name='required_documents',
            field=models.JSONField(blank=True, default=apps.schools.models_settings.get_default_required_documents, help_text='List of required document types for full active admission'),
        ),
    ]
