# Generated by Django 4.2.27 on 2026-01-19 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('O+', 'O+'), ('O-', 'O-'), ('AB+', 'AB+'), ('AB-', 'AB-')], max_length=5)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('weight_kg', models.IntegerField(blank=True, null=True)),
                ('allergies', models.TextField(blank=True, help_text='Peanuts, Dust, etc.')),
                ('chronic_conditions', models.TextField(blank=True, help_text='Asthma, Diabetes, etc.')),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=15)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to='students.student')),
            ],
        ),
        migrations.CreateModel(
            name='ClinicVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('symptom', models.CharField(help_text='Headache, Fever, Injury', max_length=200)),
                ('treatment_given', models.TextField(help_text='Given Paracetamol, Bandage applied')),
                ('sent_home', models.BooleanField(default=False, help_text='Did the parent pick them up?')),
                ('nurse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clinic_visits', to='students.student')),
            ],
        ),
    ]
