# Generated by Django 4.2.16 on 2026-01-24 07:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0004_schoolsettings_enable_class_teacher_attendance_edit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_student_middle_name_alter_student_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentNotificationLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_type', models.CharField(choices=[('ATTENDANCE', 'Attendance Alert'), ('MARKS', 'Marks Notification'), ('DISCIPLINE', 'Discipline Incident'), ('PROMOTION', 'Promotion Decision'), ('CERTIFICATE', 'Certificate Ready'), ('GENERAL', 'General Notification')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('channels_sent', models.JSONField(default=dict, help_text="{'sms': True/False, 'email': True/False, 'whatsapp': True/False}")),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('BOUNCED', 'Bounced')], default='PENDING', max_length=20)),
                ('delivery_status', models.JSONField(default=dict, help_text="{'sms': 'delivered', 'email': 'sent', 'whatsapp': 'read'}")),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ParentContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, help_text='Format: 9876543210', max_length=15)),
                ('phone_country_code', models.CharField(default='+91', help_text='e.g., +91 for India', max_length=5)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('whatsapp_enabled', models.BooleanField(default=True)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('preferred_channels', models.JSONField(default=list, help_text="['sms', 'email', 'whatsapp']")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_contact', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Parent Contacts',
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('ATTENDANCE', 'Attendance Alert'), ('MARKS', 'Marks Notification'), ('DISCIPLINE', 'Discipline Incident'), ('PROMOTION', 'Promotion Decision'), ('CERTIFICATE', 'Certificate Ready'), ('GENERAL', 'General Notification')], max_length=20)),
                ('title', models.CharField(help_text="e.g., 'Attendance Alert'", max_length=200)),
                ('body', models.TextField(help_text="e.g., 'Dear {{parent_name}}, {{student_name}}'s attendance...'")),
                ('channels', models.JSONField(default=dict, help_text="{'email': True, 'sms': True, 'whatsapp': True}")),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_templates', to='schools.school')),
            ],
            options={
                'ordering': ['category'],
            },
        ),
        migrations.CreateModel(
            name='NotificationQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('QUEUED', 'Queued'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='QUEUED', max_length=20)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('max_retries', models.PositiveIntegerField(default=3)),
                ('scheduled_at', models.DateTimeField()),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('log', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_item', to='notifications.studentnotificationlog')),
            ],
            options={
                'verbose_name_plural': 'Notification Queues',
                'ordering': ['scheduled_at'],
            },
        ),
        migrations.AddIndex(
            model_name='studentnotificationlog',
            index=models.Index(fields=['student', '-created_at'], name='notificatio_student_fb79cb_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnotificationlog',
            index=models.Index(fields=['parent', '-created_at'], name='notificatio_parent__761d6d_idx'),
        ),
        migrations.AddIndex(
            model_name='studentnotificationlog',
            index=models.Index(fields=['notification_type', '-created_at'], name='notificatio_notific_f3420e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationtemplate',
            unique_together={('school', 'category')},
        ),
    ]
