# Generated by Django 4.2.16 on 2026-01-21 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Free Trial'), ('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('ENTERPRISE', 'Enterprise')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20)),
                ('max_students', models.IntegerField(default=50, help_text='Maximum students allowed')),
                ('max_teachers', models.IntegerField(default=10, help_text='Maximum teachers allowed')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Subscription expiry', null=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='schools.school')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_schools', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SCHOOL_CREATED', 'School Created'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated'), ('PLAN_CHANGED', 'Subscription Plan Changed'), ('FEATURE_TOGGLED', 'Feature Toggled'), ('USER_CREATED', 'User Created')], max_length=25)),
                ('description', models.TextField()),
                ('metadata', models.TextField(blank=True, help_text='JSON string for additional action data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_audit_logs', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_super_admin', models.BooleanField(default=False, help_text='Full platform access')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_admin', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsageMetric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('STUDENT_COUNT', 'Active Students'), ('TEACHER_COUNT', 'Active Teachers'), ('ATTENDANCE_MARKED', 'Attendance Entries'), ('INVOICES_CREATED', 'Invoices Created'), ('GATE_PASSES_ISSUED', 'Gate Passes Issued'), ('HEALTH_VISITS', 'Health Visits')], max_length=25)),
                ('value', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_metrics', to='schools.school')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('school', 'metric_type', 'date')},
            },
        ),
        migrations.CreateModel(
            name='FeatureAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('ATTENDANCE', 'Attendance Management'), ('FINANCE', 'Finance & Invoicing'), ('HEALTH', 'Health Center'), ('GATE_PASS', 'Gate Pass System'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline Tracking'), ('TRANSFERS', 'Transfer Requests'), ('TEACHERS', 'Teacher Management'), ('ACADEMICS', 'Academics & Marks'), ('REPORTS', 'Report Cards'), ('NOTIFICATIONS', 'Notifications')], max_length=25)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now_add=True)),
                ('enabled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_access', to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Feature Access',
                'unique_together': {('school', 'feature')},
            },
        ),
    ]
