# Generated by Django 4.2.16 on 2026-01-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccess',
            name='feature',
            field=models.CharField(choices=[('STUDENTS', 'Student Management'), ('ATTENDANCE', 'Attendance Management'), ('FINANCE', 'Finance & Invoicing'), ('HEALTH', 'Health Center'), ('GATE_PASS', 'Gate Pass System'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline Tracking'), ('TRANSFERS', 'Transfer Requests'), ('TEACHERS', 'Teacher Management'), ('ACADEMICS', 'Academics & Marks'), ('REPORTS', 'Report Cards'), ('NOTIFICATIONS', 'Notifications'), ('TIMETABLE', 'Timetable & Scheduling'), ('LIBRARY', 'Library Management'), ('TRANSPORT', 'Transport Management'), ('HOSTEL', 'Hostel Management'), ('EXAMS', 'Exam Management'), ('CERTIFICATES', 'Certificate Generation')], max_length=25),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SCHOOL_CREATED', 'School Created'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated'), ('PLAN_CHANGED', 'Subscription Plan Changed'), ('FEATURE_TOGGLED', 'Feature Toggled'), ('USER_CREATED', 'User Created'), ('ADMIN_CREATED', 'School Admin Created'), ('ADMIN_DELETED', 'School Admin Deleted'), ('ADMIN_UPDATED', 'School Admin Updated'), ('FEATURE_BULK_TOGGLED', 'Features Toggled in Bulk'), ('DATA_ACCESSED', 'Platform Admin Accessed School Data'), ('PASSWORD_RESET', 'Admin Password Reset')], max_length=25),
        ),
    ]
