# Generated by Django 4.2.16 on 2026-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform_admin', '0002_alter_featureaccess_feature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featureaccess',
            name='feature',
            field=models.CharField(choices=[('ATTENDANCE', 'Attendance Management'), ('FINANCE', 'Finance & Invoicing'), ('HEALTH', 'Health Center'), ('GATE_PASS', 'Gate Pass System'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline Tracking'), ('TRANSFERS', 'Transfer Requests'), ('TEACHERS', 'Teacher Management'), ('ACADEMICS', 'Academics & Marks'), ('REPORTS', 'Report Cards'), ('NOTIFICATIONS', 'Notifications')], max_length=25),
        ),
        migrations.AlterField(
            model_name='platformauditlog',
            name='action',
            field=models.CharField(choices=[('SCHOOL_CREATED', 'School Created'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated'), ('PLAN_CHANGED', 'Subscription Plan Changed'), ('FEATURE_TOGGLED', 'Feature Toggled'), ('USER_CREATED', 'User Created')], max_length=25),
        ),
    ]
