# Generated by Django 4.2.27 on 2026-01-19 11:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ssid', models.CharField(help_text='School Specific ID / Admission Number', max_length=50)),
                ('grade', models.CharField(help_text='e.g. 10, 5, KG', max_length=10)),
                ('section', models.CharField(help_text='e.g. A, B', max_length=5)),
                ('academic_year', models.CharField(help_text='e.g. 2025-2026', max_length=9)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TRANSFERRED', 'Transferred Out'), ('GRADUATED', 'Graduated/Alumni'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'grade'],
                'unique_together': {('student', 'school', 'academic_year')},
            },
        ),
    ]
