# Generated by Django 4.2.27 on 2026-01-19 13:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'verbose_name': 'Class Enrollment'},
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='studentenrollment',
            name='ssid',
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='enrollment_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='roll_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.CharField(default='2025-2026', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='grade',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='section',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred Out'), ('ALUMNI', 'Alumni')], default='ACTIVE', max_length=20),
        ),
    ]
