# Generated by Django 4.2.16 on 2026-01-21 06:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0002_alter_studentenrollment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('year_code', models.CharField(help_text='e.g., 2025-2026', max_length=9)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('CLOSING', 'Closing (In Progress)'), ('CLOSED', 'Closed')], default='UPCOMING', max_length=10)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_years', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='schools.school')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('school', 'year_code')},
            },
        ),
        migrations.CreateModel(
            name='PromotionBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (Preview)'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('ROLLED_BACK', 'Rolled Back')], default='DRAFT', max_length=15)),
                ('total_students', models.IntegerField(default=0)),
                ('promoted_count', models.IntegerField(default=0)),
                ('retained_count', models.IntegerField(default=0)),
                ('graduated_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_log', models.TextField(blank=True, help_text='Errors encountered during processing')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_batches', to='enrollments.academicyear')),
                ('initiated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_batches', to='schools.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enrollment_id', models.UUIDField(help_text='Reference to original enrollment')),
                ('student_name', models.CharField(max_length=255)),
                ('student_suid', models.CharField(max_length=50)),
                ('from_grade', models.CharField(max_length=10)),
                ('from_section', models.CharField(max_length=5)),
                ('to_grade', models.CharField(blank=True, max_length=10)),
                ('to_section', models.CharField(blank=True, max_length=5)),
                ('action', models.CharField(choices=[('PROMOTED', 'Promoted'), ('RETAINED', 'Retained'), ('GRADUATED', 'Graduated (Alumni)'), ('FAILED', 'Failed')], max_length=15)),
                ('reason', models.TextField(blank=True, help_text='Why promoted/retained/graduated')),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='enrollments.promotionbatch')),
            ],
            options={
                'ordering': ['student_name'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_grade', models.CharField(help_text='e.g., 9', max_length=10)),
                ('to_grade', models.CharField(help_text='e.g., 10 or ALUMNI', max_length=10)),
                ('promotion_type', models.CharField(choices=[('AUTO', 'Automatic (Pass All)'), ('MARKS_BASED', 'Marks Based'), ('MANUAL', 'Manual Review')], default='AUTO', max_length=15)),
                ('action', models.CharField(choices=[('PROMOTE', 'Promote to Next Grade'), ('RETAIN', 'Retain in Same Grade'), ('GRADUATE', 'Convert to Alumni')], default='PROMOTE', max_length=10)),
                ('min_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum % to promote', max_digits=5, null=True)),
                ('auto_assign_section', models.BooleanField(default=True, help_text='Automatically assign sections after promotion')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='schools.school')),
            ],
            options={
                'ordering': ['from_grade'],
                'unique_together': {('school', 'from_grade')},
            },
        ),
        migrations.CreateModel(
            name='DataCarryForward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_type', models.CharField(choices=[('HEALTH_PROFILE', 'Health Profile'), ('DISCIPLINE_HISTORY', 'Discipline History'), ('ACHIEVEMENTS', 'Achievements'), ('GATE_PASS_HISTORY', 'Gate Pass History')], max_length=25)),
                ('carry_forward', models.BooleanField(default=True, help_text='Should this data carry forward?')),
                ('archive_instead', models.BooleanField(default=False, help_text='Archive old data instead of deleting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carryforward_rules', to='schools.school')),
            ],
            options={
                'unique_together': {('school', 'data_type')},
            },
        ),
    ]
