# Generated by Django 4.2.16 on 2026-01-21 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_schoolsettings_allow_continuation_after_10_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_student_middle_name_alter_student_gender_and_more'),
        ('enrollments', '0003_academicyear_promotionbatch_promotionrecord_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContinuationException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Why this student is allowed to continue')),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateField(blank=True, help_text='Date until exception is valid', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_continuations', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuation_exceptions', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='continuation_exceptions', to='students.student')),
            ],
            options={
                'verbose_name': 'Continuation Exception',
                'verbose_name_plural': 'Continuation Exceptions',
                'unique_together': {('school', 'student')},
            },
        ),
    ]
