# Generated by Django 4.2.16 on 2026-01-23 16:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('enrollments', '0004_continuationexception'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentenrollment',
            options={'ordering': ['-academic_year', '-created_at'], 'verbose_name': 'Class Enrollment'},
        ),
        migrations.AlterUniqueTogether(
            name='studentenrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments_closed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='is_closed',
            field=models.BooleanField(default=False, help_text='Once closed, this enrollment cannot be modified'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='is_reenrollment',
            field=models.BooleanField(default=False, help_text='Is this a re-enrollment after graduation/gap?'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='previous_enrollment',
            field=models.ForeignKey(blank=True, help_text='Link to previous enrollment if re-enrolled', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reenrollments', to='enrollments.studentenrollment'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='reenrollment_reason',
            field=models.TextField(blank=True, help_text='Why student re-enrolled (gap year, grade repetition, etc.)'),
        ),
        migrations.AddField(
            model_name='studentenrollment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred Out'), ('GRADUATED', 'Graduated'), ('COMPLETED', 'Completed (End of enrollment period)')], default='ACTIVE', max_length=20),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['student', 'academic_year', 'status'], name='enrollments_student_caea1e_idx'),
        ),
        migrations.AddIndex(
            model_name='studentenrollment',
            index=models.Index(fields=['school', 'status'], name='enrollments_school__d95ce3_idx'),
        ),
    ]
