# Generated by Django 4.2.16 on 2026-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0005_alter_studentenrollment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred Out'), ('GRADUATED', 'Graduated'), ('COMPLETED', 'Completed (End of enrollment period)'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20),
        ),
    ]
