# Generated by Django 4.2.16 on 2026-06-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0006_alter_studentenrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TRANSFERRED', 'Transferred Out'), ('GRADUATED', 'Graduated'), ('COMPLETED', 'Completed (End of enrollment period)'), ('WITHDRAWN', 'Withdrawn'), ('TEMPORARY', 'Temporary')], default='ACTIVE', max_length=20),
        ),
    ]
