# Generated by Django 4.2.16 on 2026-07-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0007_alter_studentenrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentenrollment',
            name='academic_year',
            field=models.CharField(default='', max_length=20),
        ),
    ]
