# Generated by Django 4.2.16 on 2026-07-26 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordHierarchyLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(db_index=True, max_length=100)),
                ('role_name', models.CharField(help_text='Name of the role of the user who made this edit', max_length=150)),
                ('edited_changes', models.TextField(blank=True, help_text='Summary of what was created or edited')),
                ('hierarchy_level', models.IntegerField(default=1, help_text='Hierarchy level of the role at edit time (1-101)')),
                ('action', models.CharField(default='UPDATE', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hierarchy_record_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Record Hierarchy Log',
                'verbose_name_plural': 'Record Hierarchy Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-timestamp'], name='audit_recor_content_8fbfca_idx')],
            },
        ),
    ]
