# Generated by Django 4.2.27 on 2026-01-19 11:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='artifacts/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=False, help_text='Can this be shown on public profile?')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='enrollments.studentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Verbal Warning'), ('MEDIUM', 'Written Warning'), ('HIGH', 'Suspension'), ('CRITICAL', 'Expulsion')], max_length=10)),
                ('date_incident', models.DateField()),
                ('action_taken', models.TextField(help_text='e.g. Parents called, 2 day suspension')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='enrollments.studentenrollment')),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural/Arts'), ('LEADERSHIP', 'Leadership'), ('OTHER', 'Other')], max_length=20)),
                ('date_awarded', models.DateField()),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='achievements/')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='enrollments.studentenrollment')),
            ],
        ),
    ]
