# Generated by Django 4.2.16 on 2026-01-25 19:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_student_options_student_address_line1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentYearlyAward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='e.g. 2024-2025', max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('award_type', models.CharField(choices=[('CERTIFICATE', 'Certificate'), ('AWARD', 'Award'), ('MEDAL', 'Medal'), ('TROPHY', 'Trophy'), ('CASH_PRIZE', 'Cash Prize'), ('SCHOLARSHIP', 'Scholarship'), ('APPRECIATION', 'Appreciation'), ('OTHER', 'Other')], max_length=20)),
                ('category', models.CharField(choices=[('ACADEMIC', 'Academic Excellence'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural/Arts'), ('OLYMPIAD', 'Olympiad/Competition'), ('LEADERSHIP', 'Leadership'), ('ATTENDANCE', 'Perfect Attendance'), ('DISCIPLINE', 'Good Conduct'), ('CREATIVITY', 'Creativity/Innovation'), ('COMMUNITY', 'Community Service'), ('OTHER', 'Other')], max_length=20)),
                ('level', models.CharField(choices=[('CLASS', 'Class Level'), ('SCHOOL', 'School Level'), ('INTER_SCHOOL', 'Inter-School'), ('DISTRICT', 'District Level'), ('STATE', 'State Level'), ('NATIONAL', 'National Level'), ('INTERNATIONAL', 'International')], default='SCHOOL', max_length=20)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('cash_prize_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cash_prize_currency', models.CharField(default='INR', max_length=10)),
                ('certificate_image', models.ImageField(blank=True, null=True, upload_to='yearly_awards/')),
                ('event_name', models.CharField(blank=True, max_length=200, null=True)),
                ('event_date', models.DateField(blank=True, null=True)),
                ('awarded_by', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards_created', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yearly_awards', to='students.student')),
                ('student_history', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='students.studenthistory')),
            ],
            options={
                'ordering': ['-event_date', '-created_at'],
            },
        ),
    ]
