# Generated by Django 4.2.16 on 2026-06-13 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0002_studentyearlyaward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='category',
            field=models.CharField(choices=[('CURRICULAR', 'Curricular'), ('NON_CURRICULAR', 'Non-curricular'), ('EXTRA_CURRICULAR', 'Extra-curricular'), ('ACADEMIC', 'Academic'), ('SPORTS', 'Sports'), ('CULTURAL', 'Cultural/Arts'), ('LEADERSHIP', 'Leadership'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='title',
            field=models.CharField(blank=True, default='Achievement', max_length=200),
        ),
    ]
