# Generated by Django 4.2.16 on 2026-07-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0003_alter_achievement_category_alter_achievement_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='certificate_image',
            field=models.FileField(blank=True, null=True, upload_to='achievements/'),
        ),
        migrations.AlterField(
            model_name='studentyearlyaward',
            name='certificate_image',
            field=models.FileField(blank=True, null=True, upload_to='yearly_awards/'),
        ),
    ]
