# Generated by Django 4.2.16 on 2026-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0004_alter_achievement_certificate_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='grade',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
