# Generated by Django 4.2.16 on 2026-01-26 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studenthistory_achievements_count_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0006_examscheme_schemeexam_examinstance_studentresult_and_more'),
        ('schools', '0008_schoolsettings_auto_apply_late_fee_and_more'),
        ('finance', '0002_feeschedule_feestructure_alter_feecategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('discount_type', models.CharField(choices=[('SCHOLARSHIP', 'Scholarship'), ('SIBLING', 'Sibling Discount'), ('STAFF_CHILD', 'Staff Child Discount'), ('MERIT', 'Merit-based Discount'), ('FINANCIAL_AID', 'Financial Aid'), ('EARLY_PAYMENT', 'Early Payment Discount'), ('PROMOTIONAL', 'Promotional Discount'), ('OTHER', 'Other')], max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('is_percentage', models.BooleanField(default=True)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('calculated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=True, help_text='Apply every year automatically')),
                ('reason', models.TextField(help_text='Reason for granting this discount')),
                ('supporting_documents', models.TextField(blank=True, help_text='Reference to supporting documents')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REVOKED', 'Revoked')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_approved', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts_requested', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_records', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discount_records', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeeLedger',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(max_length=20)),
                ('total_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_payments', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_discounts', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fines', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_cleared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_ledgers', to='students.student')),
            ],
            options={
                'ordering': ['-academic_year', 'student__user__first_name'],
                'unique_together': {('student', 'academic_year')},
            },
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='date',
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoice',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_number',
            field=models.CharField(blank=True, help_text='Cheque No / UPI Ref / Transaction ID', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='schools.school'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='SUCCESS', max_length=20),
        ),
        migrations.AddField(
            model_name='transaction',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_transactions', to='students.student'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='transaction_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='transaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(editable=False, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('UNPAID', 'Unpaid'), ('PARTIAL', 'Partially Paid'), ('PAID', 'Paid'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='UNPAID', max_length=10),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='collected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_collected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='reference_id',
            field=models.CharField(blank=True, help_text='Legacy field', max_length=50),
        ),
        migrations.CreateModel(
            name='LateFeeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('calculation_type', models.CharField(choices=[('FIXED', 'Fixed Amount'), ('PERCENTAGE', 'Percentage of Due Amount'), ('PER_DAY', 'Per Day Late'), ('SLAB', 'Slab-based')], default='PER_DAY', max_length=20)),
                ('fixed_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('per_day_amount', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('grace_period_days', models.PositiveIntegerField(default=7)),
                ('max_late_fee', models.DecimalField(decimal_places=2, default=0, help_text='Maximum cap on late fee', max_digits=10)),
                ('applies_to_all', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='late_fee_rules', to='schools.school')),
                ('specific_grades', models.ManyToManyField(blank=True, related_name='late_fee_rules', to='academics.grade')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.feecategory')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='finance.invoice')),
            ],
            options={
                'ordering': ['invoice', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FeeLedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entry_type', models.CharField(choices=[('CHARGE', 'Fee Charge'), ('PAYMENT', 'Payment Received'), ('DISCOUNT', 'Discount Applied'), ('FINE', 'Fine/Late Fee'), ('REFUND', 'Refund'), ('ADJUSTMENT', 'Manual Adjustment'), ('CARRIED_FORWARD', 'Carried Forward from Previous Year')], max_length=20)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries_created', to=settings.AUTH_USER_MODEL)),
                ('discount_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.discountrecord')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.invoice')),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='finance.feeledger')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.transaction')),
            ],
            options={
                'verbose_name_plural': 'Fee Ledger Entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='finance.feeledger'),
        ),
        migrations.CreateModel(
            name='FeeAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('PAYMENT', 'Payment Recorded'), ('REFUND', 'Refund Processed'), ('DISCOUNT_APPLIED', 'Discount Applied'), ('FINE_APPLIED', 'Fine Applied'), ('WAIVER', 'Fee Waived')], max_length=20)),
                ('model_type', models.CharField(choices=[('INVOICE', 'Invoice'), ('TRANSACTION', 'Transaction'), ('FEE_ASSIGNMENT', 'Fee Assignment'), ('DISCOUNT', 'Discount Record'), ('LEDGER', 'Ledger Entry'), ('FEE_STRUCTURE', 'Fee Structure'), ('FEE_SCHEDULE', 'Fee Schedule')], max_length=20)),
                ('model_id', models.CharField(max_length=50)),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_audit_logs', to='schools.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fee_audit_logs', to='students.student')),
            ],
            options={
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['school', 'performed_at'], name='finance_fee_school__4a02f6_idx'), models.Index(fields=['student', 'performed_at'], name='finance_fee_student_6e6e86_idx'), models.Index(fields=['model_type', 'model_id'], name='finance_fee_model_t_c61eaa_idx')],
            },
        ),
    ]
