# Generated by Django 4.2.16 on 2026-01-26 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_discountrecord_feeledger_remove_transaction_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='finance.invoice'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Successful'), ('PENDING', 'Pending'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed'), ('COMPLETED', 'Completed')], default='SUCCESS', max_length=20),
        ),
    ]
