# Generated by Django 4.2.16 on 2026-01-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_migrate_to_grade_config'),
        ('finance', '0004_make_invoice_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='feestructure',
            options={'ordering': ['-academic_year', 'grade__grade_order']},
        ),
        migrations.AlterModelOptions(
            name='studentfeeassignment',
            options={'ordering': ['-academic_year', '-created_at']},
        ),
        migrations.AlterField(
            model_name='bulkfeeassignment',
            name='target_grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fee_structures', to='schools.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='latefeerule',
            name='specific_grades',
            field=models.ManyToManyField(blank=True, related_name='late_fee_rules', to='schools.gradeconfiguration'),
        ),
    ]
