# Generated by Django 4.2.16 on 2026-05-04 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_migrate_to_grade_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeledgerentry',
            name='fee_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger_entries', to='finance.feecategory'),
        ),
        migrations.AlterField(
            model_name='feeschedule',
            name='schedule_type',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('BI_MONTHLY', 'Bi-Monthly (Every 2 months)'), ('QUARTERLY', 'Quarterly (Every 3 months)'), ('HALF_YEARLY', 'Half Yearly (Every 6 months)'), ('YEARLY', 'Yearly (Annual)'), ('PER_EXAM', 'Per Exam/Term'), ('CUSTOM', 'Custom')], max_length=20),
        ),
    ]
