# Generated by Django 4.2.16 on 2026-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_feeledgerentry_fee_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feeledgerentry',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='finance.invoice'),
        ),
        migrations.AlterField(
            model_name='feeledgerentry',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ledger_entries', to='finance.transaction'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='fee_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.studentfeeassignment'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='installment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='finance.feeinstallment'),
        ),
    ]
