# Generated by Django 4.2.16 on 2026-07-03 10:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0011_teacher_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0018_schoolsettings_gatepass_creation_email_body_and_more'),
        ('finance', '0007_alter_feeledgerentry_invoice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryDeduction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.CharField(help_text='Month in YYYY-MM format, e.g. 2026-07', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(help_text='Reason for the deduction')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_deductions_recorded', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to='schools.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_deductions', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
