# Generated by Django 4.2.16 on 2026-01-31 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0009_schoolsettings_enable_gatepass_print'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan', models.CharField(choices=[('FREE', 'Free Plan'), ('BASIC', 'Basic Plan'), ('PREMIUM', 'Premium Plan'), ('ENTERPRISE', 'Enterprise Plan')], default='FREE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], default='ACTIVE', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('max_students', models.IntegerField(default=50)),
                ('max_teachers', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('suspended_at', models.DateTimeField(blank=True, null=True)),
                ('suspension_reason', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_subscriptions', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_subscription', to='schools.school')),
                ('suspended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspended_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'School Subscription',
                'verbose_name_plural': 'School Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='PlatformOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='owner_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Owner',
                'verbose_name_plural': 'Platform Owners',
            },
        ),
        migrations.CreateModel(
            name='OwnerAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('SCHOOL_CREATED', 'School Created'), ('SCHOOL_UPDATED', 'School Updated'), ('SCHOOL_SUSPENDED', 'School Suspended'), ('SCHOOL_ACTIVATED', 'School Activated'), ('ADMIN_CREATED', 'School Admin Created'), ('ADMIN_UPDATED', 'School Admin Updated'), ('ADMIN_DELETED', 'School Admin Deleted'), ('PASSWORD_RESET', 'Admin Password Reset'), ('SUBSCRIPTION_CREATED', 'Subscription Created'), ('SUBSCRIPTION_UPDATED', 'Subscription Updated'), ('PLAN_CHANGED', 'Subscription Plan Changed'), ('FEATURE_TOGGLED', 'Feature Toggled'), ('FEATURE_BULK_TOGGLED', 'Features Bulk Toggled')], max_length=50)),
                ('description', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_actions', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_audit_logs', to='schools.school')),
            ],
            options={
                'verbose_name': 'Owner Audit Log',
                'verbose_name_plural': 'Owner Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureToggle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('STUDENTS', 'Student Management'), ('ATTENDANCE', 'Attendance Management'), ('FINANCE', 'Finance & Invoicing'), ('HEALTH', 'Health Center'), ('GATE_PASS', 'Gate Pass System'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline Tracking'), ('TRANSFERS', 'Transfer Requests'), ('TEACHERS', 'Teacher Management'), ('ACADEMICS', 'Academics & Marks'), ('REPORTS', 'Report Cards'), ('NOTIFICATIONS', 'Notifications'), ('TIMETABLE', 'Timetable & Scheduling'), ('LIBRARY', 'Library Management'), ('TRANSPORT', 'Transport Management'), ('HOSTEL', 'Hostel Management'), ('EXAMS', 'Exam Management'), ('CERTIFICATES', 'Certificate Generation')], max_length=50)),
                ('is_enabled', models.BooleanField(default=True)),
                ('enabled_at', models.DateTimeField(auto_now=True)),
                ('enabled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='toggled_features', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_toggles', to='schools.school')),
            ],
            options={
                'verbose_name': 'Feature Toggle',
                'verbose_name_plural': 'Feature Toggles',
                'unique_together': {('school', 'feature')},
            },
        ),
    ]
