# Generated by Django 4.2.16 on 2026-01-31 07:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0010_remove_school_name_school_academic_year_start_month_and_more'),
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='feature',
            field=models.CharField(choices=[('STUDENTS', 'Student Management'), ('TEACHERS', 'Teacher Management'), ('ATTENDANCE', 'Attendance'), ('ANNOUNCEMENTS', 'Announcements'), ('FINANCE', 'Fees & Billing'), ('ONLINE_PAYMENTS', 'Online Payments'), ('EXAMS', 'Exams & Report Cards'), ('HOMEWORK', 'Homework'), ('TRANSPORT', 'Transport'), ('HOSTEL', 'Hostel'), ('LIBRARY', 'Library'), ('INVENTORY', 'Inventory'), ('TIMETABLE', 'Timetable Automation'), ('LIVE_CLASSES', 'Live Classes'), ('AI_ANALYTICS', 'AI Analytics'), ('HEALTH', 'Health Center'), ('GATE_PASS', 'Gate Pass'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline'), ('REPORTS', 'Report Cards'), ('NOTIFICATIONS', 'Notifications'), ('CERTIFICATES', 'Certificate Generation'), ('TRANSFERS', 'Transfer Requests')], max_length=50),
        ),
        migrations.CreateModel(
            name='OnboardingChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_1_school_identity', models.BooleanField(default=False, help_text='School identity configured')),
                ('step_2_owner_admin', models.BooleanField(default=False, help_text='Owner & super admin created')),
                ('step_3_campus', models.BooleanField(default=False, help_text='Campus setup completed')),
                ('step_4_programs', models.BooleanField(default=False, help_text='Academic programs configured')),
                ('step_5_curriculum', models.BooleanField(default=False, help_text='Curriculum & subjects mapped')),
                ('step_6_features', models.BooleanField(default=False, help_text='Features enabled')),
                ('step_7_fees', models.BooleanField(default=False, help_text='Fees & payment configured')),
                ('step_8_rbac', models.BooleanField(default=False, help_text='Roles & permissions set up')),
                ('step_9_branding', models.BooleanField(default=False, help_text='Branding & communication configured')),
                ('step_10_legal', models.BooleanField(default=False, help_text='Legal & compliance completed')),
                ('admin_created', models.BooleanField(default=False, help_text='At least one admin created')),
                ('programs_created', models.BooleanField(default=False, help_text='At least one program created')),
                ('grades_added', models.BooleanField(default=False, help_text='Grades added to programs')),
                ('teachers_added', models.BooleanField(default=False, help_text='At least one teacher added')),
                ('students_uploaded', models.BooleanField(default=False, help_text='Students uploaded')),
                ('fees_configured', models.BooleanField(default=False, help_text='Fee structure configured')),
                ('is_complete', models.BooleanField(default=False, help_text='All steps completed')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_onboardings', to=settings.AUTH_USER_MODEL)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding_checklist', to='schools.school')),
            ],
            options={
                'verbose_name': 'Onboarding Checklist',
                'verbose_name_plural': 'Onboarding Checklists',
            },
        ),
    ]
