# Generated by Django 4.2.16 on 2026-01-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0002_alter_featuretoggle_feature_onboardingchecklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuretoggle',
            name='sub_features',
            field=models.JSONField(blank=True, default=dict, help_text="Granular feature flags e.g. {'health_pass': True}"),
        ),
        migrations.AlterField(
            model_name='featuretoggle',
            name='feature',
            field=models.CharField(choices=[('STUDENTS', 'Student Management'), ('TEACHERS', 'Teacher Management'), ('ATTENDANCE', 'Attendance'), ('ANNOUNCEMENTS', 'Announcements'), ('FINANCE', 'Fees & Billing'), ('ONLINE_PAYMENTS', 'Online Payments'), ('EXAMS', 'Exams & Report Cards'), ('HOMEWORK', 'Homework'), ('TRANSPORT', 'Transport'), ('HOSTEL', 'Hostel'), ('LIBRARY', 'Library'), ('INVENTORY', 'Inventory'), ('TIMETABLE', 'Timetable Automation'), ('LIVE_CLASSES', 'Live Classes'), ('AI_ANALYTICS', 'AI Analytics'), ('HEALTH', 'Health Center'), ('GATE_PASS', 'Gate Pass'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline'), ('REPORTS', 'Report Cards'), ('NOTIFICATIONS', 'Notifications'), ('CERTIFICATES', 'Certificate Generation'), ('TRANSFERS', 'Transfer Requests'), ('DATA_EXPORTS', 'Data Exports (Excel/PDF)')], max_length=50),
        ),
    ]
