# Generated by Django 4.2.16 on 2026-01-31 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_featuretoggle_sub_features_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuretoggle',
            name='feature',
            field=models.CharField(choices=[('STUDENTS', 'Students'), ('TEACHERS', 'Teachers'), ('ATTENDANCE', 'Attendance'), ('ANNOUNCEMENTS', 'Announcements'), ('FINANCE', 'Finance'), ('ONLINE_PAYMENTS', 'Online Payments'), ('EXAMS', 'Exams & Report Cards'), ('HOMEWORK', 'Homework'), ('TRANSPORT', 'Transport'), ('HOSTEL', 'Hostel'), ('LIBRARY', 'Library'), ('INVENTORY', 'Inventory'), ('TIMETABLE', 'Timetable'), ('LIVE_CLASSES', 'Live Classes'), ('AI_ANALYTICS', 'Analytics'), ('HEALTH', 'Health'), ('GATE_PASS', 'Gate Pass'), ('ACHIEVEMENTS', 'Achievements'), ('DISCIPLINE', 'Discipline'), ('REPORTS', 'Reports'), ('NOTIFICATIONS', 'Notifications'), ('CERTIFICATES', 'Certificates'), ('TRANSFERS', 'Transfers'), ('DATA_EXPORTS', 'Data Exports')], max_length=50),
        ),
    ]
