# Generated by Django 4.2.27 on 2026-01-28 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_studenthistory_achievements_count_and_more'),
        ('promotions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_class', models.CharField(max_length=50)),
                ('to_class', models.CharField(max_length=50)),
                ('from_section', models.CharField(blank=True, max_length=10)),
                ('to_section', models.CharField(blank=True, max_length=10)),
                ('graduated_on', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduation_events', to='students.student')),
            ],
            options={
                'ordering': ['-graduated_on'],
            },
        ),
    ]
