# Generated by Django 4.2.27 on 2026-01-28 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_graduationevent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GraduationEvent',
        ),
    ]
