# Generated by Django 4.2.16 on 2026-01-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_examtype_schoolacademicconfig_gradetermconfig_and_more'),
        ('accounts', '0003_remove_user_full_name_remove_user_is_school_admin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='school',
            field=models.ForeignKey(blank=True, help_text='School this user belongs to (for school admins, teachers)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='schools.school'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent')], default='STUDENT', max_length=20),
        ),
    ]
