# Generated by Django 4.2.16 on 2026-01-26 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_broadcastnotification_adminnote_broadcastreadreceipt'),
        ('academics', '0006_examscheme_schemeexam_examinstance_studentresult_and_more'),
        ('accounts', '0005_password_reset_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text='Unique permission code (e.g., students.view_student)', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Human-readable name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Detailed description')),
                ('module', models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('academics', 'Academics'), ('attendance', 'Attendance'), ('finance', 'Finance'), ('health', 'Health'), ('discipline', 'Discipline'), ('gatepass', 'Gate Pass'), ('achievements', 'Achievements'), ('transfers', 'Transfers'), ('enrollments', 'Enrollments'), ('reports', 'Reports'), ('settings', 'Settings'), ('users', 'User Management'), ('roles', 'Role Management')], max_length=50)),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('approve', 'Approve'), ('export', 'Export'), ('import', 'Import'), ('publish', 'Publish'), ('manage', 'Manage')], max_length=20)),
                ('resource', models.CharField(help_text='Resource being accessed', max_length=50)),
                ('is_sensitive', models.BooleanField(default=False, help_text='Requires extra confirmation for sensitive actions')),
                ('requires_school_context', models.BooleanField(default=True, help_text='Permission only valid within school context')),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['module', 'display_order', 'action'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('role_type', models.CharField(choices=[('CUSTOM', 'Custom Role'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('ACCOUNTANT', 'Accountant'), ('RECEPTIONIST', 'Receptionist'), ('LIBRARIAN', 'Librarian'), ('LAB_ASSISTANT', 'Lab Assistant'), ('COUNSELOR', 'Counselor'), ('SPORTS_COORDINATOR', 'Sports Coordinator')], default='CUSTOM', max_length=30)),
                ('hierarchy_level', models.IntegerField(default=1, help_text='Higher level = more authority. Admin=100, Principal=90, etc.')),
                ('is_active', models.BooleanField(default=True)),
                ('is_system_role', models.BooleanField(default=False, help_text='System roles cannot be deleted by school admins')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_roles', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission')),
                ('school', models.ForeignKey(blank=True, help_text='School this role belongs to. NULL for system-wide roles.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='schools.school')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['-hierarchy_level', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
        migrations.CreateModel(
            name='RolePermissionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('ROLE_CREATED', 'Role Created'), ('ROLE_UPDATED', 'Role Updated'), ('ROLE_DELETED', 'Role Deleted'), ('PERMISSION_ADDED', 'Permission Added'), ('PERMISSION_REMOVED', 'Permission Removed'), ('USER_ASSIGNED', 'User Assigned to Role'), ('USER_REMOVED', 'User Removed from Role')], max_length=30)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_actions', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.permission')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permission_logs', to='schools.school')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_changes_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission Log',
                'verbose_name_plural': 'Role Permission Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary role shown in profile')),
                ('valid_from', models.DateField(blank=True, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL)),
                ('grade_scope', models.ForeignKey(blank=True, help_text='Limit role to specific grade (e.g., Class 10 teacher)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assignments', to='accounts.role')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_role_assignments', to='schools.school')),
                ('section_scope', models.ForeignKey(blank=True, help_text='Limit role to specific section', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.section')),
                ('subject_scope', models.ForeignKey(blank=True, help_text='Limit role to specific subject', null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Role Assignment',
                'verbose_name_plural': 'User Role Assignments',
                'ordering': ['-is_primary', '-role__hierarchy_level'],
                'unique_together': {('user', 'role', 'school')},
            },
        ),
    ]
