# Generated by Django 4.2.16 on 2026-01-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_migrate_to_grade_config'),
        ('accounts', '0008_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='grade_scope',
            field=models.ForeignKey(blank=True, help_text='Limit role to specific grade (e.g., Class 10 teacher)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.gradeconfiguration'),
        ),
    ]
