# Generated by Django 4.2.16 on 2026-06-10 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_role_associated_user_role_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('PLATFORM_ADMIN', 'Platform Admin'), ('SCHOOL_ADMIN', 'School Admin'), ('ADMIN', 'Admin'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent'), ('ROLE', 'Role-based Login')], default='STUDENT', max_length=20),
        ),
    ]
