# Generated by Django 4.2.16 on 2026-06-10 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='module',
            field=models.CharField(choices=[('students', 'Students'), ('teachers', 'Teachers'), ('academics', 'Academics'), ('attendance', 'Attendance'), ('finance', 'Finance'), ('health', 'Health'), ('discipline', 'Discipline'), ('gatepass', 'Gate Pass'), ('achievements', 'Achievements'), ('transfers', 'Transfers'), ('enrollments', 'Enrollments'), ('reports', 'Reports'), ('settings', 'Settings'), ('users', 'User Management'), ('roles', 'Role Management'), ('transport', 'Transport'), ('library', 'Library'), ('assets', 'Assets')], max_length=50),
        ),
    ]
