# Generated by Django 4.2.16 on 2026-06-12 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_permission_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='plain_password',
            field=models.CharField(blank=True, help_text='Plain text password for email notifications', max_length=128, null=True),
        ),
    ]
