# Generated by Django 4.2.16 on 2026-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_schoolsettings_gatepass_creation_email_body_and_more'),
        ('accounts', '0014_role_plain_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='timetable_grade_scopes',
            field=models.ManyToManyField(blank=True, help_text='Grades for which this role can manage timetables', related_name='scoped_roles', to='schools.gradeconfiguration'),
        ),
    ]
