# Generated by Django 4.2.16 on 2026-07-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_timetable_created_by'),
        ('accounts', '0015_role_timetable_grade_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='syllabus_custom_subjects',
            field=models.ManyToManyField(blank=True, help_text='Custom subjects for syllabus scope', related_name='scoped_user_roles_syllabus', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='userrole',
            name='syllabus_scope_type',
            field=models.CharField(choices=[('ALL', 'All Subjects'), ('TEACHER_ASSIGNED', 'Teacher Assigned'), ('CUSTOM', 'Custom Subjects')], default='ALL', help_text='Scope of syllabus permissions', max_length=20),
        ),
    ]
