# Generated by Django 4.2.16 on 2026-07-14 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_timetable_created_by'),
        ('accounts', '0016_userrole_syllabus_custom_subjects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='syllabus_subject_scopes',
            field=models.ManyToManyField(blank=True, help_text='Allocated subjects for which this role can manage/view syllabus', related_name='scoped_syllabus_roles', to='academics.subjectmapping'),
        ),
    ]
