# Generated by Django 4.2.16 on 2026-07-14 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_timetable_created_by'),
        ('accounts', '0017_role_syllabus_subject_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='exam_subject_scopes',
            field=models.ManyToManyField(blank=True, help_text='Allocated subjects for which this role can manage/create exams', related_name='scoped_exam_roles', to='academics.subjectmapping'),
        ),
        migrations.AddField(
            model_name='role',
            name='exam_type_scopes',
            field=models.JSONField(blank=True, default=list, help_text='Exam types for which this role can manage/create exams'),
        ),
    ]
