# Generated by Django 4.2.16 on 2026-07-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_timetable_created_by'),
        ('accounts', '0018_role_exam_subject_scopes_role_exam_type_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='marks_subject_scopes',
            field=models.ManyToManyField(blank=True, help_text='Allocated subjects for which this role can enter/manage marks', related_name='scoped_marks_roles', to='academics.subjectmapping'),
        ),
    ]
