# Generated by Django 4.2.16 on 2026-07-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_timetable_created_by'),
        ('accounts', '0019_role_marks_subject_scopes'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='attendance_section_scopes',
            field=models.ManyToManyField(blank=True, help_text='Sections for which this role can view/edit attendance', related_name='scoped_attendance_roles', to='academics.section'),
        ),
    ]
