# Generated by Django 4.2.16 on 2026-07-31 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_role_attendance_section_scopes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='hierarchy_level',
            field=models.IntegerField(default=1, help_text='Role hierarchy level (1-100). Higher level = authority to edit/overwrite records created by lower roles. School Admin is fixed at 101.'),
        ),
    ]
