# Generated by Django 4.2.16 on 2026-08-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_role_hierarchy_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='student_role_scopes',
            field=models.JSONField(blank=True, default=list, help_text='Student user IDs for which this role can manage/assign roles'),
        ),
        migrations.AddField(
            model_name='role',
            name='teacher_role_scopes',
            field=models.JSONField(blank=True, default=list, help_text='Teaching staff user IDs for which this role can manage/assign roles'),
        ),
    ]
