# Generated by Django 4.2.16 on 2026-01-20 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_teacherassignment'),
        ('students', '0006_student_middle_name_alter_student_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='exam_room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='grace_marks',
            field=models.PositiveIntegerField(default=0, help_text='Admin-set grace marks'),
        ),
        migrations.AddField(
            model_name='exam',
            name='invigilators',
            field=models.ManyToManyField(blank=True, related_name='invigilated_exams', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='exam',
            name='min_attendance_percentage',
            field=models.PositiveIntegerField(default=75, help_text='Minimum attendance % to be eligible'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked - no further changes allowed'),
        ),
        migrations.AddField(
            model_name='reportcard',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='result',
            name='moderation_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderated_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='moderation_remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='result',
            name='moderation_status',
            field=models.CharField(choices=[('DRAFT', 'Draft - Not Reviewed'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved by HOD/Admin'), ('LOCKED', 'Locked - Final')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='section',
            name='capacity_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent enrollment changes'),
        ),
        migrations.AddField(
            model_name='section',
            name='co_class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_class_sections', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='section',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='affects_promotion',
            field=models.BooleanField(default=True, help_text='Whether marks affect grade promotion'),
        ),
        migrations.AddField(
            model_name='subject',
            name='included_in_board_report',
            field=models.BooleanField(default=True, help_text='Include in official board report'),
        ),
        migrations.AddField(
            model_name='subject',
            name='passing_marks',
            field=models.PositiveIntegerField(default=40, help_text='Minimum marks to pass'),
        ),
        migrations.AddField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('ACTIVITY', 'Activity/Skill')], default='CORE', max_length=20),
        ),
        migrations.AddField(
            model_name='subjectmapping',
            name='co_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='co_subject_assignments', to='teachers.teacher'),
        ),
        migrations.AddField(
            model_name='subjectmapping',
            name='exam_weightage',
            field=models.DecimalField(decimal_places=0, default=100, help_text='Percentage of total marks from exams', max_digits=3),
        ),
        migrations.AddField(
            model_name='timetable',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Lock to prevent changes'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_timetables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TemporarySubstitution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_substitutions', to=settings.AUTH_USER_MODEL)),
                ('original_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substituted_periods', to='teachers.teacher')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='substitution', to='academics.period')),
                ('substitute_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='substitution_assignments', to='teachers.teacher')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MalpracticeIncident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(help_text='Detailed account of the incident')),
                ('severity', models.CharField(choices=[('MINOR', 'Minor (Warning)'), ('MAJOR', 'Major (Action Required)'), ('SEVERE', 'Severe (Escalation)')], default='MINOR', max_length=20)),
                ('action_taken', models.TextField(blank=True, help_text='Disciplinary action or outcome')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_malpractice_actions', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_incidents', to='academics.exam')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malpractice_records', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamAbsenteeLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_eligible_for_reexam', models.BooleanField(default=False)),
                ('re_exam_date', models.DateField(blank=True, null=True)),
                ('re_exam_marks', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='absentee_log', to='academics.result')),
            ],
        ),
    ]
