# Generated by Django 4.2.16 on 2026-01-23 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_exam_exam_room_exam_grace_marks_exam_invigilators_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportcard',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.section'),
        ),
    ]
