# Generated by Django 4.2.16 on 2026-01-24 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_middle_name_alter_student_gender_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('schools', '0004_schoolsettings_enable_class_teacher_attendance_edit_and_more'),
        ('academics', '0004_result_attempt_number_result_is_reexam_of_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('instructions', models.TextField(blank=True, help_text='Detailed instructions for students')),
                ('assigned_date', models.DateField(default=django.utils.timezone.now)),
                ('due_date', models.DateField()),
                ('max_marks', models.PositiveIntegerField(default=10)),
                ('assignment_type', models.CharField(choices=[('HOMEWORK', 'Homework'), ('CLASSWORK', 'Classwork'), ('PROJECT', 'Project'), ('QUIZ', 'Quiz'), ('PRACTICE', 'Practice'), ('LAB', 'Lab Work'), ('RESEARCH', 'Research'), ('OTHER', 'Other')], default='HOMEWORK', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PUBLISHED', 'Published'), ('CLOSED', 'Closed'), ('GRADED', 'Graded')], default='DRAFT', max_length=20)),
                ('include_in_grade', models.BooleanField(default=False, help_text='Include this assignment score in final grade calculation')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.school')),
                ('section', models.ForeignKey(blank=True, help_text='Leave empty to assign to all sections of the grade', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
            ],
            options={
                'ordering': ['-assigned_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_text', models.TextField(blank=True, help_text='Text/answer submission')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='Submitted file paths')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_graded', models.BooleanField(default=False)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('feedback', models.TextField(blank=True, help_text='Teacher feedback')),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('late_penalty_applied', models.DecimalField(decimal_places=2, default=0, help_text='Marks deducted for late submission', max_digits=5)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='academics.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to='students.student')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('assignment', 'student')},
            },
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school', 'grade', 'subject'], name='academics_a_school__8fd6f2_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school', 'status'], name='academics_a_school__0ea20f_idx'),
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['created_by', 'status'], name='academics_a_created_49a3e9_idx'),
        ),
    ]
