# Generated by Django 4.2.16 on 2026-01-24 13:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0006_student_middle_name_alter_student_gender_and_more'),
        ('schools', '0005_examtype_schoolacademicconfig_gradetermconfig_and_more'),
        ('academics', '0005_assignment_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2025-2026)', max_length=9)),
                ('board', models.CharField(default='CUSTOM', help_text='Board/System (CBSE, ICSE, CUSTOM, etc.)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Is this scheme currently active?')),
                ('is_published', models.BooleanField(default=False, help_text='Is this scheme published? (cannot edit after publish)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_schemes', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schemes', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_schemes', to='schools.school')),
            ],
            options={
                'verbose_name': 'Exam Scheme',
                'ordering': ['-academic_year', 'grade'],
                'unique_together': {('school', 'grade', 'academic_year')},
            },
        ),
        migrations.CreateModel(
            name='SchemeExam',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Exam name (e.g., Unit Test 1, Term 1, Final)', max_length=100)),
                ('code', models.CharField(help_text='Code (e.g., UT1, T1, FIN)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Description of this exam')),
                ('max_marks', models.PositiveIntegerField(help_text='Maximum marks for this exam', validators=[django.core.validators.MinValueValidator(1)])),
                ('passing_marks_percent', models.DecimalField(decimal_places=2, default=33, help_text='Passing percentage for this exam', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('weightage_percent', models.DecimalField(decimal_places=2, default=0, help_text='Weight in final grade calculation', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('exam_type', models.CharField(choices=[('UNIT_TEST', 'Unit Test'), ('PERIODIC', 'Periodic Assessment'), ('TERM', 'Term Exam'), ('MID_TERM', 'Mid Term'), ('FINAL', 'Final'), ('PRACTICAL', 'Practical')], default='UNIT_TEST', max_length=20)),
                ('is_final', models.BooleanField(default=False, help_text='Include in final result calculation')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Order in which to display exams')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scheme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.examscheme')),
            ],
            options={
                'ordering': ['sequence', 'name'],
                'unique_together': {('scheme', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ExamInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft - Not Started'), ('ACTIVE', 'Active - Marks being entered'), ('SUBMITTED', 'Submitted for Review'), ('APPROVED', 'Approved by Admin'), ('PUBLISHED', 'Published - Final'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('exam_date', models.DateField(blank=True, help_text='Date of exam (optional)', null=True)),
                ('duration_minutes', models.PositiveIntegerField(default=60, help_text='Duration in minutes')),
                ('published_at', models.DateTimeField(blank=True, help_text='When was this exam published?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='academics.schemeexam')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='academics.section')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='academics.subject')),
            ],
            options={
                'ordering': ['exam__sequence', 'subject__name'],
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('marks_obtained', models.DecimalField(blank=True, decimal_places=2, help_text='Marks obtained by student', max_digits=6, null=True)),
                ('attendance_status', models.CharField(choices=[('ABSENT', 'Absent'), ('PRESENT', 'Present'), ('WITHHELD', 'Withheld')], default='PRESENT', max_length=20)),
                ('is_pass', models.BooleanField(default=False, help_text='Did student pass this exam?')),
                ('grace_marks', models.DecimalField(decimal_places=2, default=0, help_text='Grace marks awarded by admin', max_digits=6)),
                ('remarks', models.TextField(blank=True, help_text='Teacher remarks')),
                ('attempt_number', models.PositiveIntegerField(choices=[(1, 'First Attempt'), (2, 'Second Attempt (Re-exam)'), (3, 'Third Attempt')], default=1, help_text='Attempt number (1=first, 2+=re-exam)')),
                ('is_compartment', models.BooleanField(default=False, help_text='Is this a compartment exam?')),
                ('moderation_status', models.CharField(choices=[('DRAFT', 'Draft - Teacher entering marks'), ('SUBMITTED', 'Submitted - Awaiting review'), ('APPROVED', 'Approved - Can be published'), ('PUBLISHED', 'Published - Final & locked')], default='DRAFT', max_length=20)),
                ('locked_at', models.DateTimeField(blank=True, help_text='When was this result locked?', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='academics.examinstance')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheme_exam_results', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['exam_instance', 'moderation_status'], name='academics_s_exam_in_34c9d9_idx'), models.Index(fields=['student', 'attempt_number'], name='academics_s_student_2d4284_idx')],
                'unique_together': {('exam_instance', 'student', 'attempt_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamSubject',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('passing_marks', models.PositiveIntegerField(blank=True, help_text='Passing marks for this subject (leave empty to use exam default)', null=True)),
                ('is_mandatory', models.BooleanField(default=True, help_text='Is this exam mandatory for this subject?')),
                ('sequence', models.PositiveIntegerField(default=0, help_text='Order to display this subject')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_mappings', to='academics.schemeexam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_mappings', to='academics.subject')),
            ],
            options={
                'ordering': ['sequence', 'subject__name'],
                'unique_together': {('exam', 'subject')},
            },
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['school', 'status'], name='academics_e_school__509f36_idx'),
        ),
        migrations.AddIndex(
            model_name='examinstance',
            index=models.Index(fields=['section', 'status'], name='academics_e_section_9dc1ab_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='examinstance',
            unique_together={('exam', 'subject', 'section')},
        ),
    ]
