# Generated by Django 4.2.16 on 2026-01-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_migrate_to_grade_config'),
        ('finance', '0005_migrate_to_grade_config'),
        ('schools', '0011_migrate_to_grade_config'),
        ('students', '0009_migrate_to_grade_config'),
        ('academics', '0006_examscheme_schemeexam_examinstance_studentresult_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examscheme',
            options={'ordering': ['-academic_year', 'grade_config'], 'verbose_name': 'Exam Scheme'},
        ),
        migrations.AlterModelOptions(
            name='resultpromotionrule',
            options={'ordering': ['grade_config__grade_order']},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'ordering': ['grade_config__grade_order', 'section_letter']},
        ),
        migrations.AlterModelOptions(
            name='studentpromotiondecision',
            options={'ordering': ['-academic_year', '-created_at']},
        ),
        # migrations.AlterUniqueTogether(
        #     name='examscheme',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='resultpromotionrule',
        #     unique_together=set(),
        # ),
        # migrations.AlterUniqueTogether(
        #     name='section',
        #     unique_together=set(),
        # ),
        # migrations.RemoveField(
        #     model_name='studentpromotiondecision',
        #     name='from_grade',
        # ),
        # migrations.RemoveField(
        #     model_name='studentpromotiondecision',
        #     name='to_grade',
        # ),
        migrations.AddField(
            model_name='examscheme',
            name='grade_config',
            field=models.ForeignKey(blank=True, help_text='Grade level for this scheme', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_schemes', to='schools.gradeconfiguration'),
        ),
        migrations.AddField(
            model_name='resultpromotionrule',
            name='grade_config',
            field=models.ForeignKey(blank=True, help_text='Grade configuration from academic program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='schools.gradeconfiguration'),
        ),
        migrations.AddField(
            model_name='section',
            name='grade_config',
            field=models.ForeignKey(blank=True, help_text='Grade configuration from academic program', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.gradeconfiguration'),
        ),
        migrations.AddField(
            model_name='studentpromotiondecision',
            name='from_grade_config',
            field=models.ForeignKey(blank=True, help_text='Grade configuration student is being promoted from', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='schools.gradeconfiguration'),
        ),
        migrations.AddField(
            model_name='studentpromotiondecision',
            name='to_grade_config',
            field=models.ForeignKey(blank=True, help_text='Grade configuration student is being promoted to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions_to', to='schools.gradeconfiguration'),
        ),
        # migrations.AlterField(
        #     model_name='assignment',
        #     name='grade',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='schools.gradeconfiguration'),
        # ),
        # migrations.AlterField(
        #     model_name='examinstance',
        #     name='grade',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_instances', to='schools.gradeconfiguration'),
        # ),
        migrations.AlterUniqueTogether(
            name='examscheme',
            unique_together={('school', 'grade_config', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='resultpromotionrule',
            unique_together={('school', 'grade_config', 'academic_year')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('school', 'grade_config', 'section_letter')},
        ),
        # migrations.RemoveField(
        #     model_name='examscheme',
        #     name='grade',
        # ),
        # migrations.RemoveField(
        #     model_name='resultpromotionrule',
        #     name='grade',
        # ),
        # migrations.RemoveField(
        #     model_name='section',
        #     name='grade',
        # ),
        # migrations.DeleteModel(
        #     name='Grade',
        # ),
    ]
