# Generated by Django 4.2.16 on 2026-01-31 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0012_cleanup_grade_schema'),
        ('academics', '0008_cleanup_grade_schema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examscheme',
            name='grade_config',
            field=models.ForeignKey(help_text='Grade level for this scheme', on_delete=django.db.models.deletion.CASCADE, related_name='exam_schemes', to='schools.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='resultpromotionrule',
            name='grade_config',
            field=models.ForeignKey(help_text='Grade configuration from academic program', on_delete=django.db.models.deletion.CASCADE, related_name='promotion_rules', to='schools.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='section',
            name='grade_config',
            field=models.ForeignKey(help_text='Grade configuration from academic program', on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='schools.gradeconfiguration'),
        ),
        migrations.AlterField(
            model_name='studentpromotiondecision',
            name='from_grade_config',
            field=models.ForeignKey(help_text='Grade configuration student is being promoted from', on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='schools.gradeconfiguration'),
        ),
    ]
