# Generated by Django 4.2.16 on 2026-06-16 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_finalize_grade_migration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('ACTIVITY', 'Activity/Skill'), ('SPORTS_YOGA', 'Sports/Yoga')], default='CORE', max_length=20),
        ),
    ]
