# Generated by Django 4.2.16 on 2026-06-17 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='marks_locked',
            field=models.BooleanField(default=False, help_text='Locked - no further changes to marks/results allowed'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_type',
            field=models.CharField(choices=[('CORE', 'Core'), ('ELECTIVE', 'Elective'), ('ACTIVITY', 'Activity/Skill')], default='CORE', max_length=20),
        ),
    ]
