# Generated by Django 4.2.16 on 2026-06-18 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_exam_marks_locked_alter_subject_subject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='assessment_category',
            field=models.CharField(choices=[('INTERNAL', 'Internal Marks'), ('PRACTICAL', 'Practicals/Practical Exams')], default='INTERNAL', help_text='Category of assessment for marks entry', max_length=20),
        ),
    ]
