# Generated by Django 4.2.16 on 2026-07-11 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0013_result_aggregated_internal_marks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_timetables', to=settings.AUTH_USER_MODEL),
        ),
    ]
