# Generated by Django 4.2.16 on 2026-07-22 10:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_schoolsettings_gatepass_creation_email_body_and_more'),
        ('academics', '0014_timetable_created_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectEvaluation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_id', models.CharField(max_length=10)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('grades', models.JSONField(blank=True, default=dict)),
                ('is_locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_evaluations', to='schools.school')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_evaluations', to='academics.section')),
                ('subject_mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direct_evaluations', to='academics.subjectmapping')),
            ],
            options={
                'db_table': 'academics_direct_evaluation',
                'unique_together': {('school', 'section', 'subject_mapping', 'category_id')},
            },
        ),
    ]
