# Generated by Django 4.2.16 on 2026-08-09 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_directevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Maximum capacity limit for elective subject', null=True),
        ),
    ]
