'use client';

import { useState, useEffect } from 'react';
import { 
  KeyRound, ShieldCheck, Lock, CheckCircle2, Clock, 
  AlertCircle, Key, Calendar, Info, QrCode
} from 'lucide-react';
import api from '@/lib/api';

interface GatePassRecord {
  id: string;
  pass_id: string;
  secret_key: string;
  reason: string;
  status: string;
  requested_at: string;
  issued_at?: string;
  out_time?: string;
  valid_until?: string;
  scanned_at?: string;
  approval_note?: string;
  cancellation_reason?: string;
}

export default function StudentGatePassPage() {
  const [passes, setPasses] = useState<GatePassRecord[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchPasses();
  }, []);

  const fetchPasses = async () => {
    try {
      setLoading(true);
      const res = await api.get('/gatepass/passes/student_passes/');
      setPasses(res.data?.passes || []);
    } catch (err) {
      console.error('Failed to fetch gate passes', err);
      setPasses([]);
    } finally {
      setLoading(false);
    }
  };


  return (
    <div className="space-y-8 max-w-7xl mx-auto">
      {/* Header Banner */}
      <div className="bg-white p-6 rounded-3xl border border-slate-200/80 shadow-sm flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <span className="px-2.5 py-0.5 bg-slate-100 text-slate-600 rounded-lg text-xs font-bold flex items-center gap-1">
              <ShieldCheck size={13} className="text-amber-600" /> View-Only Access
            </span>
            <span className="px-2.5 py-0.5 bg-amber-50 text-amber-700 rounded-lg text-xs font-extrabold flex items-center gap-1">
              <Lock size={11} /> School Admin Synced
            </span>
          </div>
          <h1 className="text-2xl font-extrabold text-slate-900 flex items-center gap-2.5">
            <div className="p-2.5 bg-amber-50 text-amber-600 rounded-2xl">
              <KeyRound size={24} />
            </div>
            Gate Pass Registry & Secret Keys
          </h1>
          <p className="text-sm text-slate-500 mt-1">
            All secret keys and security gate passes generated for your exit & entry authorization.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="bg-amber-50 border border-amber-100 px-5 py-2.5 rounded-2xl text-right">
            <span className="text-xs text-amber-700 font-bold block">Total Passes Issued</span>
            <span className="text-xl font-black text-amber-800">
              {passes.length}
            </span>
          </div>
        </div>
      </div>

      {/* Gate Pass Table with Secret Keys */}
      <div className="bg-white rounded-3xl border border-slate-200/80 shadow-sm p-6 space-y-6">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-slate-100">
          <div>
            <h2 className="text-lg font-bold text-slate-900 flex items-center gap-2">
              <Key size={20} className="text-amber-600" /> Gate Pass History & Verification Keys
            </h2>
            <p className="text-xs text-slate-500 mt-0.5">
              Secret keys generated for verification at the school main gate.
            </p>
          </div>
          <span className="text-xs font-extrabold text-amber-700 bg-amber-50 px-3 py-1 rounded-full border border-amber-100">
            {passes.length} {passes.length === 1 ? 'Gate Pass' : 'Gate Passes'}
          </span>
        </div>

        {loading ? (
          <div className="py-12 text-center text-slate-500 font-semibold text-sm">
            Fetching security gate pass records...
          </div>
        ) : passes.length === 0 ? (
          <div className="py-12 px-4 text-center bg-slate-50 rounded-2xl border border-dashed border-slate-200 space-y-2">
            <Info size={28} className="mx-auto text-slate-400" />
            <h3 className="text-sm font-bold text-slate-800">No Gate Passes Generated</h3>
            <p className="text-xs text-slate-500 max-w-sm mx-auto">
              No exit/entry gate passes have been generated by School Admin for your account.
            </p>
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse min-w-[750px]">
              <thead>
                <tr className="border-b border-slate-100 text-xs font-bold text-slate-400 uppercase tracking-wider">
                  <th className="py-3.5 px-4">Pass ID</th>
                  <th className="py-3.5 px-4">Secret Key</th>
                  <th className="py-3.5 px-4">Reason / Purpose</th>
                  <th className="py-3.5 px-4">Out Time</th>
                  <th className="py-3.5 px-4">Valid Until</th>
                  <th className="py-3.5 px-4">Cancellation Reason</th>
                  <th className="py-3.5 px-4">Status</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 text-sm font-medium">
                {passes.map((gp) => (
                  <tr key={gp.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="py-4 px-4 font-bold font-mono text-slate-900 text-xs">
                      {gp.pass_id}
                    </td>
                    <td className="py-4 px-4">
                      <span className="px-3 py-1 bg-amber-50 text-amber-900 font-mono font-extrabold text-sm rounded-lg border border-amber-200 shadow-xs inline-flex items-center gap-1.5">
                        <Key size={13} className="text-amber-600" /> {gp.secret_key}
                      </span>
                    </td>
                    <td className="py-4 px-4 text-slate-800 text-xs font-medium">
                      {gp.reason}
                    </td>
                    <td className="py-4 px-4 text-slate-600 text-xs font-mono">
                      {gp.status === 'USED' && gp.scanned_at ? (
                        new Date(gp.scanned_at).toLocaleString('en-IN', {
                          day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit'
                        })
                      ) : gp.out_time ? (
                        gp.out_time
                      ) : (
                        '-'
                      )}
                    </td>

                    <td className="py-4 px-4 text-slate-500 text-xs font-mono">
                      {gp.valid_until ? new Date(gp.valid_until).toLocaleString('en-IN', {
                        month: 'short', day: 'numeric', hour: '2-digit', minute: '2-digit'
                      }) : '-'}
                    </td>
                    <td className="py-4 px-4 text-xs text-slate-600 font-medium">
                      {gp.cancellation_reason || (gp.status === 'CANCELLED' || gp.status === 'REJECTED' ? 'Cancelled by Admin' : '-')}
                    </td>

                    <td className="py-4 px-4">
                      {gp.status === 'APPROVED' || gp.status === 'ACTIVE' ? (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-emerald-50 text-emerald-700 font-bold text-xs rounded-full border border-emerald-200">
                          <CheckCircle2 size={13} /> Active / Ready
                        </span>
                      ) : gp.status === 'USED' ? (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-slate-100 text-slate-700 font-bold text-xs rounded-full border border-slate-200">
                          Used (Checked Out)
                        </span>
                      ) : gp.status === 'EXPIRED' ? (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-rose-50 text-rose-700 font-bold text-xs rounded-full border border-rose-200">
                          Expired
                        </span>
                      ) : gp.status === 'REJECTED' || gp.status === 'CANCELLED' ? (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-slate-100 text-slate-500 font-bold text-xs rounded-full">
                          Cancelled
                        </span>
                      ) : (
                        <span className="inline-flex items-center gap-1 px-2.5 py-1 bg-amber-50 text-amber-700 font-bold text-xs rounded-full border border-amber-200">
                          <Clock size={13} /> Pending
                        </span>
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
