# Generated by Django 4.2.27 on 2026-01-19 20:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_profile_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('UNIFORM', 'Improper Uniform / Haircut'), ('LATE', 'Late Arrival'), ('HOMEWORK', 'Incomplete Homework'), ('BEHAVIOR', 'Classroom Disruption'), ('BULLYING', 'Bullying / Fighting'), ('DEVICE', 'Confiscated Mobile/Gadget')], max_length=20)),
                ('severity', models.CharField(choices=[('LOW', 'Low (Verbal Warning)'), ('MEDIUM', 'Medium (Written Warning / Parent Call)'), ('CRITICAL', 'Critical (Suspension / Principal Meet)')], default='LOW', max_length=10)),
                ('description', models.TextField(help_text='What exactly happened?')),
                ('action_taken', models.TextField(blank=True, help_text='e.g. Sent to corridor, Called parents')),
                ('incident_date', models.DateField(auto_now_add=True)),
                ('points_deducted', models.IntegerField(default=0, help_text='Negative impact on House Points')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_records', to='students.student')),
            ],
        ),
    ]
