# Generated by Django 4.2.27 on 2026-01-19 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('students', '0003_student_profile_photo'),
        ('discipline', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KarmaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Reason for reward', max_length=100)),
                ('points', models.IntegerField(default=10, help_text='Points to add')),
                ('date', models.DateField(auto_now_add=True)),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='karma_records', to='students.student')),
            ],
        ),
    ]
