# Generated by Django 4.2.16 on 2026-01-22 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_schoolsettings_enable_class_teacher_attendance_edit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teachers', '0005_teacher_photo'),
        ('attendance', '0002_alter_attendancesession_options_and_more'),
        ('students', '0006_student_middle_name_alter_student_gender_and_more'),
        ('discipline', '0002_karmaactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceEditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('editor_role', models.CharField(choices=[('CLASS_TEACHER', 'Class Teacher'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('ADMIN', 'Admin')], max_length=20)),
                ('old_status', models.CharField(max_length=10)),
                ('new_status', models.CharField(max_length=10)),
                ('reason', models.TextField()),
                ('edited_at', models.DateTimeField(auto_now_add=True)),
                ('attendance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edit_logs', to='attendance.studentattendance')),
                ('edited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_modifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Edit Log',
                'ordering': ['-edited_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentKarma',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('POSITIVE', 'Positive'), ('NEGATIVE', 'Negative')], max_length=10)),
                ('category', models.CharField(choices=[('HAIRCUT', 'Improper Haircut'), ('NAILS', 'Long Nails'), ('UNIFORM', 'Uniform Violation'), ('ID_CARD', 'No ID Card'), ('LATE', 'Late to Class'), ('HOMEWORK', 'Incomplete Homework'), ('BEHAVIOR', 'Misbehavior'), ('ATTENDANCE_POOR', 'Poor Attendance'), ('HELPING', 'Helping Others'), ('CLEANLINESS', 'Maintaining Cleanliness'), ('LEADERSHIP', 'Leadership'), ('DISCIPLINE', 'Excellent Discipline'), ('ACADEMIC', 'Academic Excellence'), ('SPORTS', 'Sports Achievement'), ('PARTICIPATION', 'Class Participation'), ('OTHER', 'Other')], max_length=20)),
                ('points', models.IntegerField(default=1)),
                ('remark', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('academic_year', models.CharField(max_length=9)),
                ('grade', models.CharField(max_length=10)),
                ('section', models.CharField(max_length=5)),
                ('visible_to_parent', models.BooleanField(default=True)),
                ('visible_to_student', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('given_by_teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='karma_assigned', to='teachers.teacher')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_karma', to='schools.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enhanced_karma', to='students.student')),
            ],
            options={
                'verbose_name': 'Student Karma Record',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'academic_year'], name='discipline__student_95a746_idx'), models.Index(fields=['given_by_teacher', 'created_at'], name='discipline__given_b_087d08_idx')],
            },
        ),
    ]
