# Generated by Django 4.2.16 on 2026-06-13 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0003_attendanceeditlog_studentkarma'),
    ]

    operations = [
        migrations.AddField(
            model_name='karmaactivity',
            name='description',
            field=models.TextField(blank=True, help_text='Detailed description of the action', null=True),
        ),
        migrations.AlterField(
            model_name='disciplinerecord',
            name='category',
            field=models.CharField(help_text='Incident category / title', max_length=100),
        ),
    ]
