# Generated by Django 4.2.16 on 2026-07-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0004_karmaactivity_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerecord',
            name='description',
            field=models.TextField(blank=True, default='', help_text='What exactly happened?'),
        ),
    ]
