# Generated by Django 4.2.16 on 2026-07-01 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discipline', '0005_alter_disciplinerecord_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplinerecord',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Grade when incident occurred', max_length=10),
        ),
        migrations.AddField(
            model_name='karmaactivity',
            name='grade',
            field=models.CharField(blank=True, default='', help_text='Grade when karma was awarded', max_length=10),
        ),
    ]
