# Generated by Django 4.2.27 on 2026-01-20 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], default='MALE', max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='suid',
            field=models.CharField(editable=False, max_length=50, unique=True),
        ),
    ]
