# Generated by Django 4.2.16 on 2026-01-25 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_alter_teacher_tuid'),
        ('schools', '0007_broadcastnotification_adminnote_broadcastreadreceipt'),
        ('students', '0007_alter_student_options_student_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studenthistory',
            name='achievements_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='awards_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='certificates_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='class_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='days_absent',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='days_late',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='days_present',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='grade_rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='karma_points_deducted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='karma_points_earned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='net_karma',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='promotion_remarks',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='remarks_date',
            field=models.DateField(blank=True, help_text='When teacher wrote this remark', null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='schools.school'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='total_marks',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='total_students_in_class',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='total_students_in_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='total_working_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='studenthistory',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history_remarks_made', to='teachers.teacher'),
        ),
        migrations.AlterUniqueTogether(
            name='studenthistory',
            unique_together={('student', 'academic_year_name')},
        ),
    ]
