# Generated by Django 4.2.16 on 2026-01-31 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0011_migrate_to_grade_config'),
        ('students', '0008_studenthistory_achievements_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='current_grade',
        ),
        migrations.RemoveField(
            model_name='studenthistory',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grade_config',
            field=models.ForeignKey(blank=True, help_text='Current grade level', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schools.gradeconfiguration'),
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='grade_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_history', to='schools.gradeconfiguration'),
        ),
    ]
