# Generated by Django 4.2.16 on 2026-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_migrate_to_grade_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='aadhaar_last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='alumni_directory_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='apaar_id',
            field=models.CharField(blank=True, help_text='National Level ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='category',
            field=models.CharField(blank=True, help_text='GEN/OBC/SC/ST', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='custom_attributes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='student',
            name='dietary_preference',
            field=models.CharField(blank=True, help_text='Veg/Non-Veg/Jain/Halal/Allergy-specific', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='fee_concession_applicable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='house_color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_rte_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='languages_known',
            field=models.TextField(blank=True, help_text='Comma-separated languages', null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_tongue',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='nationality',
            field=models.CharField(default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='pen_id',
            field=models.CharField(blank=True, help_text='State Level ID', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='religion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
