# Generated by Django 4.2.16 on 2026-06-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0012_alter_student_latitude_alter_student_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni'), ('PENDING_ALUMNI', 'Pending Alumni'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20),
        ),
    ]
