# Generated by Django 4.2.16 on 2026-06-13 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_student_aadhaar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fee_concession_amount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
