# Generated by Django 4.2.16 on 2026-06-25 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_student_fee_concession_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('GRADUATED', 'Graduated'), ('ALUMNI', 'Alumni'), ('PENDING_ALUMNI', 'Pending Alumni'), ('TRANSFERRED', 'Transferred'), ('SUSPENDED', 'Suspended'), ('WITHDRAWN', 'Withdrawn')], default='ACTIVE', max_length=20),
        ),
    ]
