# Generated by Django 4.2.16 on 2026-06-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_alter_student_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Real contact email provided during admission', max_length=254, null=True),
        ),
    ]
