# Generated by Django 4.2.16 on 2026-06-30 06:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0018_schoolsettings_gatepass_creation_email_body_and_more'),
        ('students', '0018_add_contact_email_to_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='contact_email',
        ),
        migrations.AddField(
            model_name='studenthistory',
            name='school_name',
            field=models.CharField(blank=True, help_text='Snapshot of school name at time of recording', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='SchoolTenure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_global_id', models.CharField(db_index=True, max_length=50)),
                ('school_name', models.CharField(max_length=200)),
                ('admitted_date', models.DateField()),
                ('transferred_date', models.DateField(blank=True, null=True)),
                ('grade_from', models.CharField(blank=True, max_length=20)),
                ('grade_to', models.CharField(blank=True, max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Currently Enrolled'), ('TRANSFERRED', 'Transferred Out'), ('WITHDRAWN', 'Withdrawn'), ('GRADUATED', 'Graduated')], default='ACTIVE', max_length=20)),
                ('admitted_to_school_name', models.CharField(blank=True, max_length=200)),
                ('admitted_to_date', models.DateField(blank=True, null=True)),
                ('timeline_snapshot', models.JSONField(blank=True, null=True)),
                ('profile_snapshot', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_tenures', to='schools.school')),
            ],
            options={
                'verbose_name': 'School Tenure',
                'verbose_name_plural': 'School Tenures',
                'ordering': ['admitted_date'],
            },
        ),
    ]
