# Generated by Django 4.2.16 on 2026-05-12 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0002_vehicle_route_alter_transportassignment_route_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='school_bus_number',
            field=models.CharField(blank=True, help_text='Internal school bus number', max_length=50, null=True),
        ),
    ]
