# Generated by Django 4.2.16 on 2026-05-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0003_vehicle_school_bus_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='driver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='driver_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
