# Generated by Django 4.2.16 on 2026-05-12 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0004_alter_vehicle_driver_name_alter_vehicle_driver_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transportassignment',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='transportassignment',
            name='order',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
