# Generated by Django 4.2.16 on 2026-07-05 10:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0019_remove_student_contact_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('transport', '0005_alter_transportassignment_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('journey', models.CharField(choices=[('MORNING', 'Morning (To School)'), ('AFTERNOON', 'Afternoon (From School)')], max_length=20)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent')], default='ABSENT', max_length=20)),
                ('remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_attendance_records', to='students.student')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='transport.vehicle')),
            ],
            options={
                'ordering': ['student__user__first_name'],
                'unique_together': {('vehicle', 'student', 'date', 'journey')},
            },
        ),
    ]
