# Generated by Django 4.2.16 on 2026-08-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0006_transportattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='waypoints',
            field=models.JSONField(blank=True, help_text='List of [lat, lng] coordinates defining custom route', null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='origin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
