# Generated by Django 4.2.16 on 2026-08-22 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0007_route_waypoints_alter_route_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportattendance',
            name='arrived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
