# Generated by Django 4.2.16 on 2026-08-23 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0008_transportattendance_arrived_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='current_status',
            field=models.CharField(blank=True, help_text='e.g. REACHED_SCHOOL, LEFT_SCHOOL, IN_TRANSIT', max_length=50, null=True),
        ),
    ]
