# Generated by Django 4.2.16 on 2026-08-25 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transport', '0009_vehicle_current_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleDailyStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('reached_school', models.BooleanField(default=False)),
                ('reached_school_at', models.DateTimeField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_statuses', to='transport.vehicle')),
            ],
            options={
                'verbose_name_plural': 'Vehicle Daily Statuses',
                'unique_together': {('vehicle', 'date')},
            },
        ),
    ]
