# Generated by Django 4.2.27 on 2026-01-19 11:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('enrollments', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved by Source School'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Transfer Complete')], default='PENDING', max_length=20)),
                ('request_date', models.DateField(auto_now_add=True)),
                ('resolution_date', models.DateField(blank=True, null=True)),
                ('admin_remarks', models.TextField(blank=True)),
                ('student_enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_requests', to='enrollments.studentenrollment')),
                ('target_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_transfers', to='schools.school')),
            ],
        ),
    ]
